-- Seed data for baby_names table (300+ unique Indian names with calculated Chaldean root & ruling planet)
INSERT INTO public.baby_names (name, gender, first_letter, name_root, ruling_planet, meaning, origin, language) VALUES
('Aadhya', 'girl', 'A', 4, 'Rahu', 'First power', 'Indian', 'hi'),
('Aanya', 'girl', 'A', 9, 'Mars', 'Grace, gift', 'Indian', 'hi'),
('Aaradhya', 'girl', 'A', 7, 'Ketu', 'Worshipped', 'Indian', 'hi'),
('Aarav', 'boy', 'A', 2, 'Moon', 'Peaceful, wise', 'Indian', 'hi'),
('Aarti', 'girl', 'A', 9, 'Mars', 'Ritual worship, hymn', 'Indian', 'hi'),
('Aarush', 'boy', 'A', 9, 'Mars', 'First ray of sun', 'Indian', 'hi'),
('Abhay', 'boy', 'A', 1, 'Sun', 'Fearless', 'Indian', 'hi'),
('Abhinav', 'boy', 'A', 3, 'Jupiter', 'Novel, innovative', 'Indian', 'hi'),
('Abhishek', 'boy', 'A', 6, 'Venus', 'Anointing, ritual', 'Indian', 'hi'),
('Aditi', 'girl', 'A', 2, 'Moon', 'Boundless, mother of gods', 'Indian', 'hi'),
('Aditya', 'boy', 'A', 3, 'Jupiter', 'Sun', 'Indian', 'hi'),
('Advay', 'boy', 'A', 4, 'Rahu', 'Unique, one of a kind', 'Indian', 'hi'),
('Advik', 'boy', 'A', 5, 'Mercury', 'Unique', 'Indian', 'hi'),
('Akanksha', 'girl', 'A', 2, 'Moon', 'Desire, hope', 'Indian', 'hi'),
('Akash', 'boy', 'A', 3, 'Jupiter', 'Sky, space', 'Indian', 'hi'),
('Akshat', 'boy', 'A', 7, 'Ketu', 'Unharmed, uninjured', 'Indian', 'hi'),
('Alisha', 'girl', 'A', 5, 'Mercury', 'Protected by God', 'Indian', 'hi'),
('Alka', 'girl', 'A', 7, 'Ketu', 'Lock of hair, beauty', 'Indian', 'hi'),
('Alok', 'boy', 'A', 4, 'Rahu', 'Light, brightness', 'Indian', 'hi'),
('Aman', 'boy', 'A', 2, 'Moon', 'Peace, safety', 'Indian', 'hi'),
('Amanpreet', 'unisex', 'A', 8, 'Saturn', 'Lover of peace', 'Indian', 'hi'),
('Amartya', 'boy', 'A', 5, 'Mercury', 'Immortal', 'Indian', 'hi'),
('Amit', 'boy', 'A', 1, 'Sun', 'Boundless, infinite', 'Indian', 'hi'),
('Amrita', 'girl', 'A', 4, 'Rahu', 'Immortal, nectar', 'Indian', 'hi'),
('Anand', 'boy', 'A', 7, 'Ketu', 'Joy, bliss', 'Indian', 'hi'),
('Ananya', 'girl', 'A', 5, 'Mercury', 'Unique, matchless', 'Indian', 'hi'),
('Anaya', 'girl', 'A', 9, 'Mars', 'Caring, protected', 'Indian', 'hi'),
('Anika', 'girl', 'A', 1, 'Sun', 'Grace, goddess Durga', 'Indian', 'hi'),
('Aniket', 'boy', 'A', 9, 'Mars', 'Lord of the world, homeless', 'Indian', 'hi'),
('Anil', 'boy', 'A', 1, 'Sun', 'Wind, air', 'Indian', 'hi'),
('Anita', 'girl', 'A', 3, 'Jupiter', 'Grace, leader', 'Indian', 'hi'),
('Anjali', 'girl', 'A', 3, 'Jupiter', 'Offering, salutation', 'Indian', 'hi'),
('Ansh', 'boy', 'A', 5, 'Mercury', 'Portion, share', 'Indian', 'hi'),
('Anshika', 'girl', 'A', 9, 'Mars', 'Part, minute particle', 'Indian', 'hi'),
('Anupama', 'girl', 'A', 8, 'Saturn', 'Incomparable, unique', 'Indian', 'hi'),
('Anurag', 'boy', 'A', 9, 'Mars', 'Love, affection', 'Indian', 'hi'),
('Anvi', 'girl', 'A', 4, 'Rahu', 'Goddess, kind', 'Indian', 'hi'),
('Apoorva', 'girl', 'A', 5, 'Mercury', 'Unique, scarce', 'Indian', 'hi'),
('Apurva', 'boy', 'A', 6, 'Venus', 'Unique, unprecedented', 'Indian', 'hi'),
('Archana', 'girl', 'A', 9, 'Mars', 'Worship, homage', 'Indian', 'hi'),
('Aria', 'unisex', 'A', 5, 'Mercury', 'Melody, lioness', 'Indian', 'hi'),
('Arjun', 'boy', 'A', 6, 'Venus', 'Bright, shining', 'Indian', 'hi'),
('Arnav', 'boy', 'A', 6, 'Venus', 'Ocean, stream', 'Indian', 'hi'),
('Aryan', 'boy', 'A', 1, 'Sun', 'Noble', 'Indian', 'hi'),
('Asha', 'girl', 'A', 1, 'Sun', 'Hope, desire', 'Indian', 'hi'),
('Ashish', 'boy', 'A', 9, 'Mars', 'Blessing', 'Indian', 'hi'),
('Atharv', 'boy', 'A', 1, 'Sun', 'Knowledge, the first Veda', 'Indian', 'hi'),
('Avi', 'unisex', 'A', 8, 'Saturn', 'Sun, air', 'Indian', 'hi'),
('Avinash', 'boy', 'A', 4, 'Rahu', 'Indestructible', 'Indian', 'hi'),
('Avni', 'girl', 'A', 4, 'Rahu', 'Earth', 'Indian', 'hi'),
('Ayaan', 'boy', 'A', 9, 'Mars', 'Gift of God', 'Indian', 'hi'),
('Ayan', 'boy', 'A', 8, 'Saturn', 'Gift of God, lucky', 'Indian', 'hi'),
('Ayush', 'boy', 'A', 7, 'Ketu', 'Long life', 'Indian', 'hi'),
('Babita', 'girl', 'B', 2, 'Moon', 'Little girl', 'Indian', 'hi'),
('Bhavana', 'girl', 'B', 3, 'Jupiter', 'Feeling, emotion', 'Indian', 'hi'),
('Bhavya', 'boy', 'B', 7, 'Ketu', 'Grand, splendid', 'Indian', 'hi'),
('Bhumika', 'girl', 'B', 3, 'Jupiter', 'Role, earth', 'Indian', 'hi'),
('Bobby', 'boy', 'B', 5, 'Mercury', 'Bright fame', 'Indian', 'hi'),
('Bunty', 'boy', 'B', 9, 'Mars', 'Healthy, cute', 'Indian', 'hi'),
('Chaitali', 'girl', 'C', 1, 'Sun', 'Born in month of Chaitra', 'Indian', 'hi'),
('Charu', 'girl', 'C', 8, 'Saturn', 'Beautiful, pleasant', 'Indian', 'hi'),
('Chinmay', 'boy', 'C', 2, 'Moon', 'Full of knowledge', 'Indian', 'hi'),
('Chirag', 'boy', 'C', 6, 'Venus', 'Lamp, light', 'Indian', 'hi'),
('Chitra', 'girl', 'C', 7, 'Ketu', 'Picture, star', 'Indian', 'hi'),
('Daksh', 'boy', 'D', 6, 'Venus', 'Capable, talented', 'Indian', 'hi'),
('Darshan', 'boy', 'D', 3, 'Jupiter', 'Vision, paying respect', 'Indian', 'hi'),
('Debashish', 'boy', 'D', 2, 'Moon', 'Blessing of God', 'Indian', 'hi'),
('Deeksha', 'girl', 'D', 7, 'Ketu', 'Initiation, dedication', 'Indian', 'hi'),
('Deep', 'unisex', 'D', 4, 'Rahu', 'Lamp, light, deep', 'Indian', 'hi'),
('Deepa', 'girl', 'D', 5, 'Mercury', 'Lamp, light', 'Indian', 'hi'),
('Deepak', 'boy', 'D', 7, 'Ketu', 'Lamp, light', 'Indian', 'hi'),
('Deepali', 'girl', 'D', 9, 'Mars', 'Row of lamps', 'Indian', 'hi'),
('Dev', 'boy', 'D', 6, 'Venus', 'God, divine', 'Indian', 'hi'),
('Devansh', 'boy', 'D', 2, 'Moon', 'Part of God', 'Indian', 'hi'),
('Devendra', 'boy', 'D', 5, 'Mercury', 'King of gods, Indra', 'Indian', 'hi'),
('Devika', 'girl', 'D', 1, 'Sun', 'Little goddess', 'Indian', 'hi'),
('Dhairya', 'boy', 'D', 6, 'Venus', 'Patience, courage', 'Indian', 'hi'),
('Dhruv', 'boy', 'D', 5, 'Mercury', 'Pole star, constant', 'Indian', 'hi'),
('Dimple', 'girl', 'D', 7, 'Ketu', 'Dimple on cheek', 'Indian', 'hi'),
('Dinesh', 'boy', 'D', 5, 'Mercury', 'Lord of the day, sun', 'Indian', 'hi'),
('Divya', 'girl', 'D', 4, 'Rahu', 'Divine, brilliant', 'Indian', 'hi'),
('Divyansh', 'boy', 'D', 8, 'Saturn', 'Divine part', 'Indian', 'hi'),
('Diya', 'girl', 'D', 7, 'Ketu', 'Lamp, light', 'Indian', 'hi'),
('Drishti', 'girl', 'D', 2, 'Moon', 'Sight, vision', 'Indian', 'hi'),
('Ekta', 'girl', 'E', 3, 'Jupiter', 'Unity', 'Indian', 'hi'),
('Eva', 'girl', 'E', 3, 'Jupiter', 'Life, living one', 'Indian', 'hi'),
('Ezra', 'unisex', 'E', 6, 'Venus', 'Helper', 'Indian', 'hi'),
('Gagan', 'boy', 'G', 4, 'Rahu', 'Sky', 'Indian', 'hi'),
('Garima', 'girl', 'G', 3, 'Jupiter', 'Warmth, honor', 'Indian', 'hi'),
('Gaurav', 'boy', 'G', 1, 'Sun', 'Honor, pride', 'Indian', 'hi'),
('Gauri', 'girl', 'G', 4, 'Rahu', 'Fair-skinned, Parvati', 'Indian', 'hi'),
('Gayatri', 'girl', 'G', 4, 'Rahu', 'Mother of Vedas, chant', 'Indian', 'hi'),
('Geeta', 'girl', 'G', 9, 'Mars', 'Sacred song', 'Indian', 'hi'),
('Girish', 'boy', 'G', 6, 'Venus', 'Lord of the mountain, Shiva', 'Indian', 'hi'),
('Gopal', 'boy', 'G', 4, 'Rahu', 'Cowherd, Lord Krishna', 'Indian', 'hi'),
('Gunjan', 'girl', 'G', 3, 'Jupiter', 'Humming of bee', 'Indian', 'hi'),
('Gurpreet', 'unisex', 'G', 8, 'Saturn', 'Love of Guru', 'Indian', 'hi'),
('Gyan', 'boy', 'G', 1, 'Sun', 'Knowledge', 'Indian', 'hi'),
('Hardik', 'boy', 'H', 6, 'Venus', 'From the heart, sincere', 'Indian', 'hi'),
('Hari', 'boy', 'H', 9, 'Mars', 'Lord Vishnu, green', 'Indian', 'hi'),
('Harini', 'girl', 'H', 6, 'Venus', 'Deer, beautiful', 'Indian', 'hi'),
('Harpreet', 'unisex', 'H', 5, 'Mercury', 'Love of God', 'Indian', 'hi'),
('Harshal', 'boy', 'H', 2, 'Moon', 'Giver of joy', 'Indian', 'hi'),
('Hema', 'girl', 'H', 6, 'Venus', 'Golden, beautiful', 'Indian', 'hi'),
('Hetal', 'unisex', 'H', 9, 'Mars', 'Friendly, loving', 'Indian', 'hi'),
('Himanshu', 'boy', 'H', 3, 'Jupiter', 'Moon, cool rays', 'Indian', 'hi'),
('Hriday', 'boy', 'H', 5, 'Mercury', 'Heart', 'Indian', 'hi'),
('Inaaya', 'girl', 'I', 1, 'Sun', 'Care, concern', 'Indian', 'hi'),
('Inderjeet', 'unisex', 'I', 5, 'Mercury', 'Victorious like Indra', 'Indian', 'hi'),
('Indrajeet', 'boy', 'I', 1, 'Sun', 'Conqueror of Indra', 'Indian', 'hi'),
('Indu', 'girl', 'I', 7, 'Ketu', 'Moon', 'Indian', 'hi'),
('Ira', 'girl', 'I', 4, 'Rahu', 'Earth, goddess Saraswati', 'Indian', 'hi'),
('Ishaan', 'boy', 'I', 7, 'Ketu', 'Sun, lord Shiva', 'Indian', 'hi'),
('Ishika', 'girl', 'I', 4, 'Rahu', 'Paint brush, sacred arrow', 'Indian', 'hi'),
('Ishita', 'girl', 'I', 6, 'Venus', 'Desired, supreme', 'Indian', 'hi'),
('Ishwar', 'boy', 'I', 9, 'Mars', 'Supreme God', 'Indian', 'hi'),
('Jaspreet', 'unisex', 'J', 2, 'Moon', 'Praise of God', 'Indian', 'hi'),
('Jatin', 'boy', 'J', 3, 'Jupiter', 'Disciplined, Lord Shiva', 'Indian', 'hi'),
('Jaya', 'girl', 'J', 4, 'Rahu', 'Victory', 'Indian', 'hi'),
('Jitendra', 'boy', 'J', 5, 'Mercury', 'Conqueror of senses', 'Indian', 'hi'),
('Jiya', 'girl', 'J', 4, 'Rahu', 'Heart, life', 'Indian', 'hi'),
('Juhi', 'girl', 'J', 4, 'Rahu', 'Jasmine flower', 'Indian', 'hi'),
('Jyoti', 'girl', 'J', 5, 'Mercury', 'Light, flame', 'Indian', 'hi'),
('Kabir', 'boy', 'K', 8, 'Saturn', 'Great, noble', 'Indian', 'hi'),
('Kajal', 'girl', 'K', 8, 'Saturn', 'Kohl, eyeliner', 'Indian', 'hi'),
('Kalyani', 'girl', 'K', 5, 'Mercury', 'Auspicious, blessed', 'Indian', 'hi'),
('Kanchan', 'girl', 'K', 4, 'Rahu', 'Gold', 'Indian', 'hi'),
('Karan', 'boy', 'K', 2, 'Moon', 'Firstborn of Kunti, helper', 'Indian', 'hi'),
('Karishma', 'girl', 'K', 1, 'Sun', 'Miracle, favor', 'Indian', 'hi'),
('Kartik', 'boy', 'K', 3, 'Jupiter', 'Month of light, son of Shiva', 'Indian', 'hi'),
('Kavita', 'girl', 'K', 6, 'Venus', 'Poem', 'Indian', 'hi'),
('Kavya', 'unisex', 'K', 2, 'Moon', 'Poetry', 'Indian', 'hi'),
('Khushi', 'girl', 'K', 4, 'Rahu', 'Happiness, joy', 'Indian', 'hi'),
('Kian', 'boy', 'K', 9, 'Mars', 'Grace of God', 'Indian', 'hi'),
('Kiara', 'girl', 'K', 7, 'Ketu', 'Dark-haired, bright', 'Indian', 'hi'),
('Kiran', 'girl', 'K', 2, 'Moon', 'Ray of light', 'Indian', 'hi'),
('Kirpal', 'unisex', 'K', 8, 'Saturn', 'Kind, merciful', 'Indian', 'hi'),
('Kirti', 'girl', 'K', 1, 'Sun', 'Fame, glory', 'Indian', 'hi'),
('Komal', 'girl', 'K', 8, 'Saturn', 'Soft, tender', 'Indian', 'hi'),
('Krishna', 'boy', 'K', 1, 'Sun', 'Dark, divine', 'Indian', 'hi'),
('Krrish', 'boy', 'K', 6, 'Venus', 'Short form of Krishna', 'Indian', 'hi'),
('Kshitij', 'boy', 'K', 8, 'Saturn', 'Horizon', 'Indian', 'hi'),
('Kuldeep', 'unisex', 'K', 6, 'Venus', 'Light of the family', 'Indian', 'hi'),
('Kunwar', 'boy', 'K', 4, 'Rahu', 'Prince', 'Indian', 'hi'),
('Kush', 'boy', 'K', 7, 'Ketu', 'Son of Lord Rama', 'Indian', 'hi'),
('Kusum', 'girl', 'K', 3, 'Jupiter', 'Flower', 'Indian', 'hi'),
('Kyra', 'girl', 'K', 6, 'Venus', 'Light, throne', 'Indian', 'hi'),
('Laksh', 'boy', 'L', 5, 'Mercury', 'Aim, goal', 'Indian', 'hi'),
('Lalit', 'boy', 'L', 3, 'Jupiter', 'Beautiful, elegant', 'Indian', 'hi'),
('Larisa', 'girl', 'L', 2, 'Moon', 'Cheerful', 'Indian', 'hi'),
('Lata', 'girl', 'L', 9, 'Mars', 'Vine, creeper', 'Indian', 'hi'),
('Leela', 'girl', 'L', 8, 'Saturn', 'Divine play, drama', 'Indian', 'hi'),
('Luv', 'boy', 'L', 6, 'Venus', 'Son of Lord Rama', 'Indian', 'hi'),
('Madhav', 'boy', 'M', 3, 'Jupiter', 'Lord Krishna, sweet', 'Indian', 'hi'),
('Madhavi', 'girl', 'M', 4, 'Rahu', 'Creeper with honey, spring', 'Indian', 'hi'),
('Madhu', 'girl', 'M', 2, 'Moon', 'Honey, sweet', 'Indian', 'hi'),
('Mahesh', 'boy', 'M', 5, 'Mercury', 'Lord Shiva, great ruler', 'Indian', 'hi'),
('Mahika', 'girl', 'M', 5, 'Mercury', 'Earth, fragrance', 'Indian', 'hi'),
('Mallika', 'girl', 'M', 6, 'Venus', 'Jasmine, queen', 'Indian', 'hi'),
('Manan', 'boy', 'M', 7, 'Ketu', 'Thinking, reflection', 'Indian', 'hi'),
('Manish', 'boy', 'M', 1, 'Sun', 'Lord of the mind, wise', 'Indian', 'hi'),
('Manisha', 'girl', 'M', 2, 'Moon', 'Intellect, desire', 'Indian', 'hi'),
('Manoj', 'boy', 'M', 9, 'Mars', 'Born of mind, Cupid', 'Indian', 'hi'),
('Manpreet', 'unisex', 'M', 7, 'Ketu', 'Pleasing mind', 'Indian', 'hi'),
('Mansi', 'girl', 'M', 5, 'Mercury', 'Intellect, voice', 'Indian', 'hi'),
('Mayank', 'boy', 'M', 5, 'Mercury', 'Moon', 'Indian', 'hi'),
('Meenal', 'girl', 'M', 5, 'Mercury', 'Precious gem, fish', 'Indian', 'hi'),
('Megha', 'girl', 'M', 9, 'Mars', 'Cloud, rain', 'Indian', 'hi'),
('Milind', 'boy', 'M', 9, 'Mars', 'Honeybee', 'Indian', 'hi'),
('Mira', 'girl', 'M', 8, 'Saturn', 'Devotee, ocean', 'Indian', 'hi'),
('Mishka', 'girl', 'M', 7, 'Ketu', 'Gift of love', 'Indian', 'hi'),
('Mitali', 'girl', 'M', 5, 'Mercury', 'Friendly, sweet', 'Indian', 'hi'),
('Mohan', 'boy', 'M', 4, 'Rahu', 'Charming, Lord Krishna', 'Indian', 'hi'),
('Muskan', 'girl', 'M', 3, 'Jupiter', 'Smile', 'Indian', 'hi'),
('Myra', 'girl', 'M', 8, 'Saturn', 'Beloved, sweet', 'Indian', 'hi'),
('Naira', 'girl', 'N', 1, 'Sun', 'Shining, bright', 'Indian', 'hi'),
('Nakul', 'boy', 'N', 8, 'Saturn', 'Pandava prince', 'Indian', 'hi'),
('Nalini', 'girl', 'N', 7, 'Ketu', 'Lotus, sweet nectar', 'Indian', 'hi'),
('Naman', 'boy', 'N', 7, 'Ketu', 'Salutation, bowing', 'Indian', 'hi'),
('Namrata', 'girl', 'N', 9, 'Mars', 'Modesty, politeness', 'Indian', 'hi'),
('Nandini', 'girl', 'N', 4, 'Rahu', 'Daughter, pleasing one', 'Indian', 'hi'),
('Naveen', 'boy', 'N', 9, 'Mars', 'New, fresh', 'Indian', 'hi'),
('Navneet', 'unisex', 'N', 4, 'Rahu', 'Fresh butter, always new', 'Indian', 'hi'),
('Navya', 'girl', 'N', 5, 'Mercury', 'New, young', 'Indian', 'hi'),
('Neetu', 'girl', 'N', 7, 'Ketu', 'Beautiful, pure', 'Indian', 'hi'),
('Neha', 'girl', 'N', 7, 'Ketu', 'Love, rain', 'Indian', 'hi'),
('Neil', 'boy', 'N', 5, 'Mercury', 'Blue, champion', 'Indian', 'hi'),
('Nidhi', 'girl', 'N', 7, 'Ketu', 'Treasure, wealth', 'Indian', 'hi'),
('Nihal', 'boy', 'N', 6, 'Venus', 'Happy, content', 'Indian', 'hi'),
('Niranjan', 'boy', 'N', 3, 'Jupiter', 'Pure, spotless', 'Indian', 'hi'),
('Nirmala', 'girl', 'N', 8, 'Saturn', 'Clean, pure', 'Indian', 'hi'),
('Nirvaan', 'unisex', 'N', 3, 'Jupiter', 'Liberation, bliss', 'Indian', 'hi'),
('Nisha', 'girl', 'N', 6, 'Venus', 'Night', 'Indian', 'hi'),
('Nishant', 'boy', 'N', 6, 'Venus', 'End of night, dawn', 'Indian', 'hi'),
('Nitara', 'girl', 'N', 5, 'Mercury', 'Deeply rooted', 'Indian', 'hi'),
('Nupur', 'girl', 'N', 9, 'Mars', 'Anklet, sound', 'Indian', 'hi'),
('Om', 'boy', 'O', 2, 'Moon', 'Sacred sound', 'Indian', 'hi'),
('Pallavi', 'girl', 'P', 5, 'Mercury', 'New leaves, branch', 'Indian', 'hi'),
('Pankaj', 'boy', 'P', 9, 'Mars', 'Lotus flower', 'Indian', 'hi'),
('Parag', 'boy', 'P', 6, 'Venus', 'Pollen grains, fame', 'Indian', 'hi'),
('Pari', 'girl', 'P', 3, 'Jupiter', 'Fairy, angel', 'Indian', 'hi'),
('Parth', 'boy', 'P', 2, 'Moon', 'Arjun, king', 'Indian', 'hi'),
('Pawan', 'boy', 'P', 3, 'Jupiter', 'Wind, sacred', 'Indian', 'hi'),
('Payal', 'girl', 'P', 5, 'Mercury', 'Anklet', 'Indian', 'hi'),
('Pinky', 'girl', 'P', 8, 'Saturn', 'Sweet, small finger', 'Indian', 'hi'),
('Piyush', 'boy', 'P', 6, 'Venus', 'Nectar, sweet water', 'Indian', 'hi'),
('Pooja', 'girl', 'P', 6, 'Venus', 'Worship, prayer', 'Indian', 'hi'),
('Poonam', 'girl', 'P', 5, 'Mercury', 'Full moon night', 'Indian', 'hi'),
('Prabhjot', 'unisex', 'P', 3, 'Jupiter', 'Light of God', 'Indian', 'hi'),
('Pramod', 'boy', 'P', 8, 'Saturn', 'Joy, delight', 'Indian', 'hi'),
('Pranav', 'boy', 'P', 5, 'Mercury', 'Sacred syllable Om', 'Indian', 'hi'),
('Prashant', 'boy', 'P', 2, 'Moon', 'Very calm, peaceful', 'Indian', 'hi'),
('Pratima', 'girl', 'P', 3, 'Jupiter', 'Icon, statue', 'Indian', 'hi'),
('Pratyush', 'boy', 'P', 3, 'Jupiter', 'Morning, sun', 'Indian', 'hi'),
('Preeti', 'girl', 'P', 7, 'Ketu', 'Love, affection', 'Indian', 'hi'),
('Prisha', 'girl', 'P', 2, 'Moon', 'Beloved, gift of God', 'Indian', 'hi'),
('Priya', 'girl', 'P', 4, 'Rahu', 'Beloved, dear', 'Indian', 'hi'),
('Priyanka', 'girl', 'P', 3, 'Jupiter', 'Beautiful, lovable act', 'Indian', 'hi'),
('Puneet', 'boy', 'P', 6, 'Venus', 'Pure, clean', 'Indian', 'hi'),
('Rachana', 'girl', 'R', 9, 'Mars', 'Creation, layout', 'Indian', 'hi'),
('Radha', 'girl', 'R', 4, 'Rahu', 'Prosperous, beloved of Krishna', 'Indian', 'hi'),
('Raghav', 'boy', 'R', 9, 'Mars', 'Lord Rama, descendant of Raghu', 'Indian', 'hi'),
('Raghu', 'boy', 'R', 8, 'Saturn', 'Swift, ancestor of Rama', 'Indian', 'hi'),
('Ragini', 'girl', 'R', 4, 'Rahu', 'Melody, music', 'Indian', 'hi'),
('Rahul', 'boy', 'R', 8, 'Saturn', 'Conqueror of all miseries', 'Indian', 'hi'),
('Rajendra', 'boy', 'R', 3, 'Jupiter', 'King of kings', 'Indian', 'hi'),
('Rajesh', 'boy', 'R', 8, 'Saturn', 'King of kings', 'Indian', 'hi'),
('Rakesh', 'boy', 'R', 9, 'Mars', 'Lord of the full moon day', 'Indian', 'hi'),
('Ram', 'boy', 'R', 7, 'Ketu', 'Lord Rama, pleasing', 'Indian', 'hi'),
('Raman', 'boy', 'R', 4, 'Rahu', 'Pleasing, beloved', 'Indian', 'hi'),
('Ramesh', 'boy', 'R', 2, 'Moon', 'Ruler of Lakshmi, Vishnu', 'Indian', 'hi'),
('Ranbir', 'boy', 'R', 4, 'Rahu', 'Brave warrior', 'Indian', 'hi'),
('Ranjana', 'girl', 'R', 7, 'Ketu', 'Delightful, pleasing', 'Indian', 'hi'),
('Ranjeet', 'boy', 'R', 5, 'Mercury', 'Victorious in battle', 'Indian', 'hi'),
('Ranveer', 'boy', 'R', 8, 'Saturn', 'Hero of the battle', 'Indian', 'hi'),
('Rashmi', 'girl', 'R', 7, 'Ketu', 'Sunbeam, ray', 'Indian', 'hi'),
('Raveena', 'girl', 'R', 7, 'Ketu', 'Sunny, bright', 'Indian', 'hi'),
('Reet', 'unisex', 'R', 7, 'Ketu', 'Tradition, custom', 'Indian', 'hi'),
('Rekha', 'girl', 'R', 6, 'Venus', 'Line, art', 'Indian', 'hi'),
('Renu', 'girl', 'R', 9, 'Mars', 'Atom, sand particle', 'Indian', 'hi'),
('Reva', 'girl', 'R', 5, 'Mercury', 'River Narmada', 'Indian', 'hi'),
('Reyansh', 'boy', 'R', 4, 'Rahu', 'Ray of light', 'Indian', 'hi'),
('Riaan', 'unisex', 'R', 1, 'Sun', 'Little king', 'Indian', 'hi'),
('Richa', 'girl', 'R', 3, 'Jupiter', 'Vedic verse, praise', 'Indian', 'hi'),
('Riddhi', 'girl', 'R', 8, 'Saturn', 'Prosperity, wealth', 'Indian', 'hi'),
('Rinki', 'girl', 'R', 2, 'Moon', 'Noble, sweet', 'Indian', 'hi'),
('Rishaan', 'boy', 'R', 9, 'Mars', 'Good human being', 'Indian', 'hi'),
('Rishi', 'boy', 'R', 3, 'Jupiter', 'Sage, saint', 'Indian', 'hi'),
('Ritu', 'girl', 'R', 4, 'Rahu', 'Season', 'Indian', 'hi'),
('Ritvik', 'boy', 'R', 7, 'Ketu', 'Priest', 'Indian', 'hi'),
('Riya', 'girl', 'R', 5, 'Mercury', 'Singer, graceful', 'Indian', 'hi'),
('Rocky', 'boy', 'R', 6, 'Venus', 'Strong ruler', 'Indian', 'hi'),
('Rohan', 'boy', 'R', 2, 'Moon', 'Ascending, red-haired', 'Indian', 'hi'),
('Rohit', 'boy', 'R', 1, 'Sun', 'Red, sun', 'Indian', 'hi'),
('Ronav', 'boy', 'R', 3, 'Jupiter', 'Joyful', 'Indian', 'hi'),
('Roopa', 'girl', 'R', 7, 'Ketu', 'Beautiful, blessed form', 'Indian', 'hi'),
('Rudra', 'boy', 'R', 6, 'Venus', 'Lord Shiva', 'Indian', 'hi'),
('Rupali', 'girl', 'R', 3, 'Jupiter', 'Very beautiful', 'Indian', 'hi'),
('Rupesh', 'boy', 'R', 2, 'Moon', 'Lord of beauty', 'Indian', 'hi'),
('Saanvi', 'girl', 'S', 8, 'Saturn', 'Goddess Lakshmi', 'Indian', 'hi'),
('Sachin', 'boy', 'S', 9, 'Mars', 'Pure, Lord Indra', 'Indian', 'hi'),
('Sadhana', 'girl', 'S', 2, 'Moon', 'Meditation, practice', 'Indian', 'hi'),
('Sai', 'unisex', 'S', 5, 'Mercury', 'Divine, master', 'Indian', 'hi'),
('Saira', 'girl', 'S', 8, 'Saturn', 'Traveller, princess', 'Indian', 'hi'),
('Sakshi', 'girl', 'S', 6, 'Venus', 'Witness, observer', 'Indian', 'hi'),
('Saloni', 'girl', 'S', 2, 'Moon', 'Beautiful, dark-skinned', 'Indian', 'hi'),
('Samar', 'boy', 'S', 2, 'Moon', 'Battle, evening', 'Indian', 'hi'),
('Samarth', 'boy', 'S', 2, 'Moon', 'Capable, efficient', 'Indian', 'hi'),
('Sameer', 'boy', 'S', 2, 'Moon', 'Breeze, pleasant companion', 'Indian', 'hi'),
('Sandeep', 'boy', 'S', 4, 'Rahu', 'A lighted lamp', 'Indian', 'hi'),
('Sandhya', 'girl', 'S', 2, 'Moon', 'Evening, twilight', 'Indian', 'hi'),
('Sangita', 'girl', 'S', 9, 'Mars', 'Music, singer', 'Indian', 'hi'),
('Sanjay', 'boy', 'S', 3, 'Jupiter', 'Victorious, Dhritarashtra''s charioteer', 'Indian', 'hi'),
('Sara', 'girl', 'S', 7, 'Ketu', 'Princess, pure', 'Indian', 'hi'),
('Sarabjeet', 'unisex', 'S', 6, 'Venus', 'Victorious overall', 'Indian', 'hi'),
('Sarita', 'girl', 'S', 3, 'Jupiter', 'River', 'Indian', 'hi'),
('Satyajeet', 'boy', 'S', 7, 'Ketu', 'Conqueror of truth', 'Indian', 'hi'),
('Saurabh', 'boy', 'S', 2, 'Moon', 'Fragrance', 'Indian', 'hi'),
('Savita', 'girl', 'S', 7, 'Ketu', 'Sun', 'Indian', 'hi'),
('Seema', 'girl', 'S', 9, 'Mars', 'Boundary, limit', 'Indian', 'hi'),
('Shailendra', 'boy', 'S', 3, 'Jupiter', 'King of mountains', 'Indian', 'hi'),
('Shailesh', 'boy', 'S', 8, 'Saturn', 'Lord of mountain', 'Indian', 'hi'),
('Shalini', 'girl', 'S', 1, 'Sun', 'Modest, dignified', 'Indian', 'hi'),
('Shanaya', 'girl', 'S', 8, 'Saturn', 'First ray of sun', 'Indian', 'hi'),
('Shashank', 'boy', 'S', 7, 'Ketu', 'Moon', 'Indian', 'hi'),
('Shaurya', 'boy', 'S', 1, 'Sun', 'Bravery', 'Indian', 'hi'),
('Shikhar', 'boy', 'S', 1, 'Sun', 'Peak, summit', 'Indian', 'hi'),
('Shila', 'girl', 'S', 4, 'Rahu', 'Rock, stone', 'Indian', 'hi'),
('Shilpa', 'girl', 'S', 3, 'Jupiter', 'Stone, statue, skill', 'Indian', 'hi'),
('Shivay', 'boy', 'S', 8, 'Saturn', 'Lord Shiva', 'Indian', 'hi'),
('Shraddha', 'girl', 'S', 7, 'Ketu', 'Faith, devotion', 'Indian', 'hi'),
('Shreya', 'girl', 'S', 8, 'Saturn', 'Auspicious, excellent', 'Indian', 'hi'),
('Shreyas', 'boy', 'S', 2, 'Moon', 'Good fortune, prosperity', 'Indian', 'hi'),
('Shruti', 'girl', 'S', 3, 'Jupiter', 'Vedic text, hearing', 'Indian', 'hi'),
('Shweta', 'girl', 'S', 6, 'Venus', 'White, pure', 'Indian', 'hi'),
('Shyam', 'boy', 'S', 5, 'Mercury', 'Dark, Lord Krishna', 'Indian', 'hi'),
('Siddharth', 'boy', 'S', 2, 'Moon', 'One who has accomplished a goal', 'Indian', 'hi'),
('Siddhi', 'girl', 'S', 9, 'Mars', 'Achievement, power', 'Indian', 'hi'),
('Simran', 'girl', 'S', 7, 'Ketu', 'Remembrance, meditation', 'Indian', 'hi'),
('Sneha', 'girl', 'S', 1, 'Sun', 'Friendship, love', 'Indian', 'hi'),
('Snehal', 'girl', 'S', 4, 'Rahu', 'Friendly, loving', 'Indian', 'hi'),
('Sohan', 'boy', 'S', 3, 'Jupiter', 'Handsome, charming', 'Indian', 'hi'),
('Sonali', 'girl', 'S', 2, 'Moon', 'Golden', 'Indian', 'hi'),
('Sonia', 'girl', 'S', 8, 'Saturn', 'Golden, wise', 'Indian', 'hi'),
('Sudha', 'girl', 'S', 1, 'Sun', 'Nectar, pure water', 'Indian', 'hi'),
('Sudhir', 'boy', 'S', 3, 'Jupiter', 'Very wise, resolute', 'Indian', 'hi'),
('Sujata', 'girl', 'S', 7, 'Ketu', 'Of good caste, well-born', 'Indian', 'hi'),
('Suman', 'girl', 'S', 1, 'Sun', 'Flower, good-minded', 'Indian', 'hi'),
('Sumit', 'boy', 'S', 9, 'Mars', 'Well measured, good friend', 'Indian', 'hi'),
('Sunil', 'boy', 'S', 9, 'Mars', 'Dark blue, sapphire', 'Indian', 'hi'),
('Sunita', 'girl', 'S', 2, 'Moon', 'Well behaved, polite', 'Indian', 'hi'),
('Sunny', 'boy', 'S', 2, 'Moon', 'Cheerful, bright', 'Indian', 'hi'),
('Suresh', 'boy', 'S', 6, 'Venus', 'Ruler of gods, Indra', 'Indian', 'hi'),
('Sushma', 'girl', 'S', 4, 'Rahu', 'Beautiful woman', 'Indian', 'hi'),
('Swapnil', 'boy', 'S', 9, 'Mars', 'Dreamy, seen in dream', 'Indian', 'hi'),
('Swati', 'girl', 'S', 6, 'Venus', 'Star, pure water drop', 'Indian', 'hi'),
('Tanmay', 'boy', 'T', 7, 'Ketu', 'Engrossed, absorbed', 'Indian', 'hi'),
('Tanuja', 'girl', 'T', 9, 'Mars', 'Daughter', 'Indian', 'hi'),
('Tanvi', 'girl', 'T', 8, 'Saturn', 'Beautiful, delicate', 'Indian', 'hi'),
('Tanya', 'girl', 'T', 3, 'Jupiter', 'Of the family, fairy princess', 'Indian', 'hi'),
('Tara', 'girl', 'T', 8, 'Saturn', 'Star', 'Indian', 'hi'),
('Tarun', 'boy', 'T', 9, 'Mars', 'Young, youthful', 'Indian', 'hi'),
('Tejas', 'boy', 'T', 5, 'Mercury', 'Brilliance, radiance', 'Indian', 'hi'),
('Tejaswi', 'girl', 'T', 3, 'Jupiter', 'Bright, brilliant', 'Indian', 'hi'),
('Tulsi', 'girl', 'T', 8, 'Saturn', 'Holy basil plant', 'Indian', 'hi'),
('Tushar', 'boy', 'T', 3, 'Jupiter', 'Snow, fine drops of water', 'Indian', 'hi'),
('Uday', 'boy', 'U', 3, 'Jupiter', 'To rise, dawn', 'Indian', 'hi'),
('Ujjwal', 'boy', 'U', 9, 'Mars', 'Bright, clear', 'Indian', 'hi'),
('Uma', 'girl', 'U', 2, 'Moon', 'Goddess Parvati, light', 'Indian', 'hi'),
('Urvashi', 'girl', 'U', 6, 'Venus', 'Celestial maiden', 'Indian', 'hi'),
('Usha', 'girl', 'U', 6, 'Venus', 'Dawn, morning light', 'Indian', 'hi'),
('Utkarsh', 'boy', 'U', 5, 'Mercury', 'Prosperity, advancement', 'Indian', 'hi'),
('Vaibhav', 'boy', 'V', 4, 'Rahu', 'Richness, grandeur', 'Indian', 'hi'),
('Vaishali', 'girl', 'V', 3, 'Jupiter', 'Historical city, grand', 'Indian', 'hi'),
('Vanya', 'girl', 'V', 5, 'Mercury', 'Gracious gift of God', 'Indian', 'hi'),
('Varsha', 'girl', 'V', 9, 'Mars', 'Rain, season', 'Indian', 'hi'),
('Varun', 'boy', 'V', 2, 'Moon', 'Lord of water', 'Indian', 'hi'),
('Vasudha', 'girl', 'V', 8, 'Saturn', 'Earth, giver of wealth', 'Indian', 'hi'),
('Vedant', 'boy', 'V', 7, 'Ketu', 'Knowledge of Vedas', 'Indian', 'hi'),
('Veena', 'girl', 'V', 4, 'Rahu', 'Lute, instrument', 'Indian', 'hi'),
('Veer', 'boy', 'V', 9, 'Mars', 'Brave', 'Indian', 'hi'),
('Vibhuti', 'boy', 'V', 7, 'Ketu', 'Sacred ash, glory', 'Indian', 'hi'),
('Vicky', 'boy', 'V', 4, 'Rahu', 'Victorious', 'Indian', 'hi'),
('Vihaan', 'boy', 'V', 1, 'Sun', 'Dawn, new beginning', 'Indian', 'hi'),
('Vijay', 'boy', 'V', 1, 'Sun', 'Victory', 'Indian', 'hi'),
('Vikas', 'boy', 'V', 4, 'Rahu', 'Development, progress', 'Indian', 'hi'),
('Vikram', 'boy', 'V', 7, 'Ketu', 'Valor, power', 'Indian', 'hi'),
('Vikrant', 'boy', 'V', 3, 'Jupiter', 'Powerful, courageous', 'Indian', 'hi'),
('Vimal', 'girl', 'V', 6, 'Venus', 'Pure, clean', 'Indian', 'hi'),
('Vinay', 'boy', 'V', 5, 'Mercury', 'Politeness, modesty', 'Indian', 'hi'),
('Vinita', 'girl', 'V', 9, 'Mars', 'Modest, simple', 'Indian', 'hi'),
('Vipin', 'boy', 'V', 3, 'Jupiter', 'Forest, woods', 'Indian', 'hi'),
('Virat', 'boy', 'V', 5, 'Mercury', 'Majestic, giant', 'Indian', 'hi'),
('Vishal', 'boy', 'V', 1, 'Sun', 'Huge, grand', 'Indian', 'hi'),
('Vivaan', 'boy', 'V', 2, 'Moon', 'Full of life', 'Indian', 'hi'),
('Vivek', 'boy', 'V', 2, 'Moon', 'Wisdom, judgment', 'Indian', 'hi'),
('Yamini', 'girl', 'Y', 4, 'Rahu', 'Night, dark sky', 'Indian', 'hi'),
('Yash', 'boy', 'Y', 1, 'Sun', 'Fame, glory', 'Indian', 'hi'),
('Yashaswi', 'girl', 'Y', 3, 'Jupiter', 'Famous, successful', 'Indian', 'hi'),
('Yogesh', 'boy', 'Y', 6, 'Venus', 'Lord of yoga, Shiva', 'Indian', 'hi'),
('Yug', 'boy', 'Y', 1, 'Sun', 'Era, age', 'Indian', 'hi'),
('Yuvaan', 'boy', 'Y', 2, 'Moon', 'Youthful', 'Indian', 'hi'),
('Yuvan', 'boy', 'Y', 1, 'Sun', 'Youthful, healthy', 'Indian', 'hi'),
('Zara', 'girl', 'Z', 2, 'Moon', 'Blooming flower', 'Indian', 'hi');