-- Phase 1d: LUCKY ATTRIBUTES seed (numbers 1-9,11,22,33 x en/hi/hinglish)
-- Matches app getLuckyAttributes() conventions. Additive, safe to re-run.
DELETE FROM public.lucky_attributes WHERE number IN (1,2,3,4,5,6,7,8,9,11,22,33);
INSERT INTO public.lucky_attributes (number, language, lucky_numbers, lucky_days, lucky_colors, lucky_directions) VALUES
(1, 'en', '{1,10,19,28}', ARRAY['Sunday','Monday']::text[], ARRAY['Gold','Orange','Yellow']::text[], ARRAY['East']::text[]),
(1, 'hi', '{1,10,19,28}', ARRAY['रविवार','सोमवार']::text[], ARRAY['सुनहरा','नारंगी','पीला']::text[], ARRAY['पूर्व']::text[]),
(1, 'hinglish', '{1,10,19,28}', ARRAY['Sunday (Ravivaar)','Monday (Somvaar)']::text[], ARRAY['Gold','Orange','Yellow']::text[], ARRAY['East (Poorab)']::text[]),
(2, 'en', '{2,11,20,29}', ARRAY['Monday','Friday']::text[], ARRAY['White','Cream','Green']::text[], ARRAY['North']::text[]),
(2, 'hi', '{2,11,20,29}', ARRAY['सोमवार','शुक्रवार']::text[], ARRAY['सफ़ेद','क्रीम','हरा']::text[], ARRAY['उत्तर']::text[]),
(2, 'hinglish', '{2,11,20,29}', ARRAY['Monday (Somvaar)','Friday (Shukravaar)']::text[], ARRAY['White','Cream','Green']::text[], ARRAY['North (Uttar)']::text[]),
(3, 'en', '{3,12,21,30}', ARRAY['Thursday','Friday']::text[], ARRAY['Yellow','Purple','Pink']::text[], ARRAY['Northeast']::text[]),
(3, 'hi', '{3,12,21,30}', ARRAY['गुरुवार','शुक्रवार']::text[], ARRAY['पीला','बैंगनी','गुलाबी']::text[], ARRAY['उत्तर-पूर्व']::text[]),
(3, 'hinglish', '{3,12,21,30}', ARRAY['Thursday (Guruvaar)','Friday (Shukravaar)']::text[], ARRAY['Yellow','Purple','Pink']::text[], ARRAY['Northeast']::text[]),
(4, 'en', '{4,13,22,31}', ARRAY['Saturday','Sunday']::text[], ARRAY['Blue','Grey','Khaki']::text[], ARRAY['Southwest']::text[]),
(4, 'hi', '{4,13,22,31}', ARRAY['शनिवार','रविवार']::text[], ARRAY['नीला','धूसर','खाकी']::text[], ARRAY['दक्षिण-पश्चिम']::text[]),
(4, 'hinglish', '{4,13,22,31}', ARRAY['Saturday (Shanivaar)','Sunday (Ravivaar)']::text[], ARRAY['Blue','Grey','Khaki']::text[], ARRAY['Southwest']::text[]),
(5, 'en', '{5,14,23}', ARRAY['Wednesday','Friday']::text[], ARRAY['Green','Turquoise','White']::text[], ARRAY['North']::text[]),
(5, 'hi', '{5,14,23}', ARRAY['बुधवार','शुक्रवार']::text[], ARRAY['हरा','फ़िरोज़ी','सफ़ेद']::text[], ARRAY['उत्तर']::text[]),
(5, 'hinglish', '{5,14,23}', ARRAY['Wednesday (Budhvaar)','Friday (Shukravaar)']::text[], ARRAY['Green','Turquoise','White']::text[], ARRAY['North (Uttar)']::text[]),
(6, 'en', '{6,15,24}', ARRAY['Friday','Wednesday']::text[], ARRAY['Blue','Pink','White']::text[], ARRAY['Northwest']::text[]),
(6, 'hi', '{6,15,24}', ARRAY['शुक्रवार','बुधवार']::text[], ARRAY['नीला','गुलाबी','सफ़ेद']::text[], ARRAY['उत्तर-पश्चिम']::text[]),
(6, 'hinglish', '{6,15,24}', ARRAY['Friday (Shukravaar)','Wednesday (Budhvaar)']::text[], ARRAY['Blue','Pink','White']::text[], ARRAY['Northwest']::text[]),
(7, 'en', '{7,16,25}', ARRAY['Monday','Sunday']::text[], ARRAY['White','Yellow','Green']::text[], ARRAY['Northwest']::text[]),
(7, 'hi', '{7,16,25}', ARRAY['सोमवार','रविवार']::text[], ARRAY['सफ़ेद','पीला','हरा']::text[], ARRAY['उत्तर-पश्चिम']::text[]),
(7, 'hinglish', '{7,16,25}', ARRAY['Monday (Somvaar)','Sunday (Ravivaar)']::text[], ARRAY['White','Yellow','Green']::text[], ARRAY['Northwest']::text[]),
(8, 'en', '{8,17,26}', ARRAY['Saturday','Thursday']::text[], ARRAY['Black','Blue','Grey']::text[], ARRAY['West']::text[]),
(8, 'hi', '{8,17,26}', ARRAY['शनिवार','गुरुवार']::text[], ARRAY['काला','नीला','धूसर']::text[], ARRAY['पश्चिम']::text[]),
(8, 'hinglish', '{8,17,26}', ARRAY['Saturday (Shanivaar)','Thursday (Guruvaar)']::text[], ARRAY['Black','Blue','Grey']::text[], ARRAY['West (Paschim)']::text[]),
(9, 'en', '{9,18,27}', ARRAY['Tuesday','Thursday']::text[], ARRAY['Red','Crimson','Pink']::text[], ARRAY['South']::text[]),
(9, 'hi', '{9,18,27}', ARRAY['मंगलवार','गुरुवार']::text[], ARRAY['लाल','गहरा लाल','गुलाबी']::text[], ARRAY['दक्षिण']::text[]),
(9, 'hinglish', '{9,18,27}', ARRAY['Tuesday (Mangalvaar)','Thursday (Guruvaar)']::text[], ARRAY['Red','Crimson','Pink']::text[], ARRAY['South (Dakshin)']::text[]),
(11, 'en', '{11,2,20,29}', ARRAY['Monday','Friday']::text[], ARRAY['Silver','White','Violet']::text[], ARRAY['North']::text[]),
(11, 'hi', '{11,2,20,29}', ARRAY['सोमवार','शुक्रवार']::text[], ARRAY['चाँदी','सफ़ेद','बैंगनी']::text[], ARRAY['उत्तर']::text[]),
(11, 'hinglish', '{11,2,20,29}', ARRAY['Monday (Somvaar)','Friday (Shukravaar)']::text[], ARRAY['Silver','White','Violet']::text[], ARRAY['North (Uttar)']::text[]),
(22, 'en', '{22,4,13,31}', ARRAY['Saturday','Thursday']::text[], ARRAY['Coral','Tan','Cream']::text[], ARRAY['Southwest']::text[]),
(22, 'hi', '{22,4,13,31}', ARRAY['शनिवार','गुरुवार']::text[], ARRAY['मूँगा','भूरा','क्रीम']::text[], ARRAY['दक्षिण-पश्चिम']::text[]),
(22, 'hinglish', '{22,4,13,31}', ARRAY['Saturday (Shanivaar)','Thursday (Guruvaar)']::text[], ARRAY['Coral','Tan','Cream']::text[], ARRAY['Southwest']::text[]),
(33, 'en', '{33,6,15,24}', ARRAY['Friday','Thursday']::text[], ARRAY['Turquoise','Pink','Blue']::text[], ARRAY['Northwest']::text[]),
(33, 'hi', '{33,6,15,24}', ARRAY['शुक्रवार','गुरुवार']::text[], ARRAY['फ़िरोज़ी','गुलाबी','नीला']::text[], ARRAY['उत्तर-पश्चिम']::text[]),
(33, 'hinglish', '{33,6,15,24}', ARRAY['Friday (Shukravaar)','Thursday (Guruvaar)']::text[], ARRAY['Turquoise','Pink','Blue']::text[], ARRAY['Northwest']::text[]);