-- ============================================================
-- Phase 1a: SOUL URGE number meanings (English)
-- Additive seed for public.number_meanings — category = 'soul_urge'
-- Numbers: 1-9, 11, 22, 33  | language: en
-- Safe to re-run.
-- ============================================================

DELETE FROM public.number_meanings WHERE category = 'soul_urge' AND language = 'en';

INSERT INTO public.number_meanings (number, category, language, title, purpose, strengths, challenges, careers, relationships, health, spiritual) VALUES
(1, 'soul_urge', 'en', 'A Heart That Craves Independence',
 'Deep down, your heart longs to stand on its own and be recognized as original. You feel most alive when you are leading, creating something new, or proving you can do it your way. Your inner drive is to be first and free.',
 '{"Inner courage","Self-belief","Pioneering desire","Determination"}',
 '{"Hidden need for approval","Loneliness at the top","Resisting interdependence"}',
 '{"Leadership roles","Solo ventures","Creative innovation"}',
 'You secretly want a partner who admires your strength yet meets you as an equal. Vulnerability is your growth edge.',
 'Suppressed frustration shows as tension. Honoring your need for autonomy keeps you well.',
 'Your soul learns that true independence includes letting others in.'),
(2, 'soul_urge', 'en', 'A Heart That Craves Harmony',
 'Your deepest desire is for peace, closeness, and loving connection. You long to be needed, to belong, and to feel emotional safety. Inner contentment comes from harmony with the people you love.',
 '{"Emotional depth","Capacity for love","Sensitivity","Devotion"}',
 '{"Fear of rejection","People-pleasing","Losing self in others"}',
 '{"Supportive partnerships","Care work","Mediation"}',
 'You crave deep, secure bonds. Choose people who value your tenderness rather than exploit it.',
 'Emotional turmoil unsettles your stomach and nerves. Peace is literally healing for you.',
 'Your soul learns that you can love deeply without disappearing.'),
(3, 'soul_urge', 'en', 'A Heart That Craves Expression',
 'Your inner self yearns to create, to be seen, and to spread joy. You feel fulfilled when you can express what is inside you — through words, art, or laughter — and when others delight in it.',
 '{"Creative longing","Warmth","Playfulness","Emotional openness"}',
 '{"Need for constant validation","Scattering feelings","Avoiding hard emotions"}',
 '{"Creative arts","Communication","Entertainment"}',
 'You want a partner who celebrates and inspires you. Beneath the sparkle, you long to be truly understood.',
 'Bottled-up feelings affect throat and mood. Expression is your release valve.',
 'Your soul learns to express truth, not just charm.'),
(4, 'soul_urge', 'en', 'A Heart That Craves Security',
 'Deep down you long for stability, order, and a solid foundation you can trust. You feel at peace when life is dependable and your efforts build something lasting. Security is your quiet treasure.',
 '{"Loyalty","Steadiness","Inner discipline","Reliability"}',
 '{"Fear of instability","Rigidity born of insecurity","Difficulty relaxing"}',
 '{"Structured work","Long-term projects","Stewardship"}',
 'You want a steady, faithful partner you can build a life with. Let love be a refuge, not another duty.',
 'Worry settles in your back and joints. Trusting life loosens the grip.',
 'Your soul learns that real security is inner, not only built of bricks.'),
(5, 'soul_urge', 'en', 'A Heart That Craves Freedom',
 'Your deepest desire is for freedom, variety, and new experience. You feel alive when nothing fences you in and the next adventure is open. Your heart resists anything that feels like a cage.',
 '{"Love of life","Adaptability","Curiosity","Boldness"}',
 '{"Fear of being trapped","Restlessness in love","Avoiding commitment"}',
 '{"Travel","Dynamic roles","Variety-rich work"}',
 'You want a partner who is also an adventure, not an anchor. Freedom and devotion can live together.',
 'Restless energy needs outlets, or it turns to excess. Movement keeps you steady.',
 'Your soul learns that the deepest freedom is found within, not in constant escape.'),
(6, 'soul_urge', 'en', 'A Heart That Craves to Love and Be Loved',
 'Your inner self longs for a loving home, family, and the chance to care for others. You feel complete when you are nurturing, protecting, and creating harmony for those you love.',
 '{"Deep caring","Loyalty","Desire to protect","Sense of beauty"}',
 '{"Over-responsibility","Needing to be needed","Self-neglect"}',
 '{"Family-centered work","Healing","Creating beautiful spaces"}',
 'You want devotion and a shared home. Make sure your giving is met, not taken for granted.',
 'You carry others'' stress in your heart. Boundaries keep your caregiving sustainable.',
 'Your soul learns to receive love as freely as it gives.'),
(7, 'soul_urge', 'en', 'A Heart That Craves Truth',
 'Deep within, you long for understanding, solitude, and meaning beneath the surface. You feel fulfilled when you grasp how things truly work and touch something sacred or profound.',
 '{"Inner depth","Love of truth","Spiritual yearning","Quiet strength"}',
 '{"Emotional guardedness","Withdrawing when hurt","Loneliness"}',
 '{"Research","Spiritual or analytical work","Specialist depth"}',
 'You want a soul-deep, honest connection. Let trusted people past your inner walls.',
 'Mental overactivity disturbs your sleep. Quiet and nature restore you.',
 'Your soul learns that wisdom is meant to be shared, not hidden.'),
(8, 'soul_urge', 'en', 'A Heart That Craves Achievement',
 'Your deepest desire is for success, recognition, and the power to shape your world. You feel fulfilled when your efforts produce real results and you can provide abundantly.',
 '{"Ambition","Drive","Resilience","Desire to provide"}',
 '{"Tying self-worth to results","Hidden insecurity","Difficulty resting"}',
 '{"Business","Leadership","Wealth building"}',
 'You want a partner who respects your drive and stands beside you. Let love be a place where you do not have to perform.',
 'Pressure targets heart and digestion. Worth is not measured in output.',
 'Your soul learns that fulfillment comes from purpose, not just accumulation.'),
(9, 'soul_urge', 'en', 'A Heart That Craves to Give',
 'Deep down you long to make a difference, to heal, and to love humanity broadly. You feel complete when your life serves something greater than yourself.',
 '{"Compassion","Idealism","Generosity","Emotional wisdom"}',
 '{"Saving everyone but yourself","Difficulty with personal intimacy","Holding on to old pain"}',
 '{"Service professions","Arts with a message","Humanitarian roles"}',
 'You love widely; remember the person beside you needs your focused presence too.',
 'You absorb the world''s sorrow. Emotional release keeps you healthy.',
 'Your soul learns to give from overflow and to let the past go.'),
(11, 'soul_urge', 'en', 'A Heart That Craves to Inspire (Master)',
 'Your inner self longs to uplift and awaken others, to live by intuition, and to connect with something higher. You feel fulfilled when you inspire and when your sensitivity finds a meaningful purpose.',
 '{"Spiritual longing","Intuitive depth","Idealism","Inspirational warmth"}',
 '{"Nervous sensitivity","Self-doubt","Feeling misunderstood"}',
 '{"Inspirational or healing work","Teaching","Creative-spiritual roles"}',
 'You want a partner who honors your inner world and steadies your sensitivity.',
 'Your fine-tuned nerves need grounding and gentle routines.',
 'Your soul learns to trust its light and turn sensitivity into service.'),
(22, 'soul_urge', 'en', 'A Heart That Craves Lasting Impact (Master)',
 'Deep within, you long to build something that truly matters and serves many. You feel fulfilled when grand vision becomes real, lasting good in the world.',
 '{"Visionary longing","Drive to build","Discipline","Desire to serve at scale"}',
 '{"Crushing self-expectation","Fear of your own potential","Overwork"}',
 '{"Large-scale building","Systems and institutions","Visionary leadership"}',
 'You want a partner who believes in your mission and helps you stay human within it.',
 'The weight you carry needs release — rest is not a luxury but fuel.',
 'Your soul learns to ground vast potential into patient, practical good.'),
(33, 'soul_urge', 'en', 'A Heart That Craves to Heal Through Love (Master)',
 'Your deepest desire is to love unconditionally and to heal others through compassion. You feel complete when your presence comforts and uplifts those who suffer.',
 '{"Boundless compassion","Healing devotion","Wisdom","Selfless love"}',
 '{"Giving until empty","Carrying everyone''s pain","Neglecting your own needs"}',
 '{"Healing","Spiritual teaching","Compassionate service"}',
 'Love is your reason for being. Choose those who replenish you as you pour out for others.',
 'Your heart needs as much care as you give. Self-compassion is essential medicine.',
 'Your soul learns that healing others begins with healing yourself.');
