-- ============================================================
-- Phase 1b: DESTINY + SOUL URGE meanings (Hinglish)
-- Additive seed for public.number_meanings
-- Numbers: 1-9, 11, 22, 33  | language: hinglish
-- Safe to re-run.
-- ============================================================

DELETE FROM public.number_meanings WHERE category IN ('destiny','soul_urge') AND language = 'hinglish';

-- ---------- DESTINY ----------
INSERT INTO public.number_meanings (number, category, language, title, purpose, strengths, challenges, careers, relationships, health, spiritual) VALUES
(1, 'destiny', 'hinglish', 'Pioneer Ka Destiny',
 'Aapke naam mein leadership aur original soch ka vibration hai. Aap naye ideas start karne, sabse aage khade hone aur kuch aisa banane ke liye ho jo pehle nahi tha. Aapka destiny self-reliant banna aur doosron ko inspire karna hai.',
 '{"Natural leadership","Originality","Achieve karne ki drive","Decisiveness","Self-motivation"}',
 '{"Dominating dikhna","Slow logon par impatience","Help maangne mein difficulty"}',
 '{"Founder","Director","Inventor","Department head","Independent consultant"}',
 'Aap wahan best dete ho jahan aapki independence respect ho. Order dene ke bajaye decisions share karna seekho.',
 'Sab kuch akele sambhalne se tension aur BP badh sakta hai. Movement aur kaam delegate karna aapko bachata hai.',
 'Aapka spiritual kaam ego ke bina lead karna hai — apni strength se doosron ko upar uthana.'),
(2, 'destiny', 'hinglish', 'Diplomat Ka Destiny',
 'Aapke naam ka vibration partnership, sensitivity aur quiet influence ka hai. Aap logon ko jodne, mediate karne aur force ke bajaye cooperation se success paane ke liye ho.',
 '{"Diplomacy","Deep intuition","Patience","Loyalty","Detail par dhyan"}',
 '{"Criticism par over-sensitive","Conflict se bachna","Self-doubt"}',
 '{"Counselor","Mediator","HR specialist","Designer","Team coordinator"}',
 'Aap love mein devoted aur tender ho. Partner mein khud ko khone se bacho — aapki needs bhi equally matter karti hain.',
 'Emotional stress aapke nervous system aur digestion ko affect karta hai. Calm routine balance deti hai.',
 'Aapka path inner strength banana hai taaki gentleness weakness nahi, choice ban jaye.'),
(3, 'destiny', 'hinglish', 'Communicator Ka Destiny',
 'Aapke naam mein expression, creativity aur joy ki energy hai. Aap words, art ya performance se communicate karne aur doosron ka mood uplift karne ke liye ho.',
 '{"Verbal aur artistic talent","Optimism","Charisma","Imagination","Social ease"}',
 '{"Energy bikherna","Depth se bachna","Mood swings"}',
 '{"Writer","Performer","Marketer","Designer","Public speaker"}',
 'Aap love mein hansi aur warmth late ho, par partner ko aapka focus bhi chahiye — charm jitni asaani se attention bhi do.',
 'Throat aur skin aapki emotional state dikhate hain. Creative outlets aapko healthy rakhte hain.',
 'Aapka task apni awaaz ka use meaning ke liye karna hai, sirf applause ke liye nahi.'),
(4, 'destiny', 'hinglish', 'Builder Ka Destiny',
 'Aapke naam ka vibration structure, discipline aur reliability ka hai. Aap aisi solid foundation banane ke liye ho jo aapke baad bhi tike. Aapka destiny steady, honest mehnat se milta hai.',
 '{"Discipline","Trustworthiness","Practical skill","Endurance","Loyalty"}',
 '{"Rigidity","Change ka resistance","Exhaustion tak kaam"}',
 '{"Engineer","Architect","Operations manager","Accountant","Builder"}',
 'Aap dependable, committed partner ho. Warmth aur spontaneity ko aane do — sirf structure apno ko cold lag sakta hai.',
 'Bones, joints aur back aapka stress carry karte hain. Regular rest aur stretching zaroori hai.',
 'Aapka path discipline mein flexibility paana hai — apni hi walls ka kaidi bane bina.'),
(5, 'destiny', 'hinglish', 'Explorer Ka Destiny',
 'Aapke naam mein freedom, change aur adventure ka vibration hai. Aap life ko widely experience karne, adapt karne aur doosron ko bina dar change apnana sikhane ke liye ho.',
 '{"Adaptability","Magnetism","Quick thinking","Courage","Versatility"}',
 '{"Restlessness","Commit karne mein difficulty","Excess ki tendency"}',
 '{"Travel/hospitality","Sales","Journalism","Entrepreneur","Trainer"}',
 'Aapko aisa partner chahiye jo space de aur aapki curiosity share kare. Freedom aur loyalty saath reh sakte hain.',
 'Aapki nervous energy ko grounding chahiye — addictions aur burnout se bacho.',
 'Aapka kaam inner freedom paana hai, taaki use har naye experience mein na dhundho.'),
(6, 'destiny', 'hinglish', 'Nurturer Ka Destiny',
 'Aapke naam ka vibration responsibility, care aur harmony ka hai. Aap family aur community ki seva, healing aur beauty-balance banane ke liye ho.',
 '{"Compassion","Responsibility","Artistic sense","Healing presence","Loyalty"}',
 '{"Over-giving","Worry","Apno ke prati perfectionism"}',
 '{"Teacher","Healthcare","Counselor","Interior designer","Chef"}',
 'Aap deeply aur protectively pyaar karte ho. Martyrdom se bacho — doosron ko bhi aapki care karne do.',
 'Heart aur circulation aapka emotional load dikhate hain. Boundaries aapke liye medicine hain.',
 'Aapka path fullness se seva karna hai, depletion se nahi — dene aur self-love mein balance.'),
(7, 'destiny', 'hinglish', 'Seeker Ka Destiny',
 'Aapke naam mein wisdom, analysis aur inner truth ka vibration hai. Aap study karne, cheezon ki hidden nature samajhne aur deep insight share karne ke liye ho.',
 '{"Analytical mind","Intuition","Independence","Depth of thought","Specialist focus"}',
 '{"Isolation","Over-thinking","Doosron par trust karne mein difficulty"}',
 '{"Researcher","Analyst","Scientist","Philosopher","Spiritual teacher"}',
 'Love mein aapko intellectual aur soul connection chahiye; shallow bonds thaka dete hain. Logon ko apni inner world mein aane do.',
 'Mental fatigue aur sleep aapke watch points hain. Solitude restore karta hai, par isolation drain karta hai.',
 'Aapka path wisdom share karna hai, hoard karna nahi — solitude ko service mein badalna.'),
(8, 'destiny', 'hinglish', 'Executive Ka Destiny',
 'Aapke naam ka vibration power, ambition aur material mastery ka hai. Aap enterprises lead karne, resources manage karne aur abundance banane — phir use wisely use karne — ke liye ho.',
 '{"Business instinct","Authority","Resilience","Organization","Scale ki vision"}',
 '{"Workaholism","Control issues","Worth ko money se jodna"}',
 '{"Executive","Entrepreneur","Investor","Lawyer","Real estate"}',
 'Love mein aapko respect aur shared ambition chahiye. Soften ho — relationships deals nahi hain jo manage karne hain.',
 'Stress heart aur digestion ko target karta hai. Health ke bina success ka matlab kam hai.',
 'Aapka path yeh seekhna hai ki sachi power inner hai — aur material success ko greater good ke liye use karna.'),
(9, 'destiny', 'hinglish', 'Humanitarian Ka Destiny',
 'Aapke naam mein compassion, wisdom aur universal service ka vibration hai. Aap humanity ko dene, wide scale par healing karne aur cycles ko grace se complete karne ke liye ho.',
 '{"Compassion","Broad wisdom","Generosity","Artistic depth","Forgiveness"}',
 '{"Emotional overwhelm","Letting go mein difficulty","Self-sacrifice"}',
 '{"Humanitarian work","Medicine","Teaching","Arts","Counseling"}',
 'Aap universally pyaar karte ho, kabhi intimacy ki keemat par. Saamne wale person ke liye present raho.',
 'Aap doosron ka dard absorb karte ho — emotional boundaries aapki energy bachati hain.',
 'Aapka path khud ko khoye bina dena aur jo complete ho gaya use chhodna hai.'),
(11, 'destiny', 'hinglish', 'Inspirer Ka Destiny (Master)',
 'Aapke naam mein 11 ka master vibration hai — illumination aur spiritual inspiration. Aap intuition, vision aur example se doosron ko jagane ke liye ho. Aapka destiny light banna hai, sirf leader nahi.',
 '{"Tez intuition","Inspirational presence","Visionary insight","Sensitivity","Idealism"}',
 '{"Nervous tension","Pressure mein self-doubt","Apni sensitivity se overwhelmed hona"}',
 '{"Spiritual teacher","Artist","Counselor","Visionary founder","Writer"}',
 'Aapko aisa partner chahiye jo aapki sensitivity samjhe aur mission mein saath de. Grounding love aapko steady karta hai.',
 'Aapka nervous system bahut fine-tuned hai — grounding practices aur rest essential hain.',
 'Aapka path apne inner light par trust karke use anxiety nahi, service mein lagana hai.'),
(22, 'destiny', 'hinglish', 'Master Builder Ka Destiny (Master)',
 'Aapke naam mein 22 ka master vibration hai — badi vision ko lasting reality mein badalne ki power. Aap bade scale par build karne ke liye ho: institutions, movements ya aise kaam jo bahut logon ki seva karein.',
 '{"Large-scale vision","Practical execution","Leadership","Discipline","Lasting impact"}',
 '{"Khud par bhaari pressure","Apni power par doubt","Workaholism"}',
 '{"Bade organization head","Architect","Systems builder","Social leader","Innovator"}',
 'Aapko aisa partner chahiye jo aapke mission ko support kare, usse compete na kare.',
 'Aapki ambition ka weight body-mind par padta hai — pace karo, rest bhi kaam ka hissa hai.',
 'Aapka path vast spiritual potential ko bahut logon ke practical bhale mein utarna hai.'),
(33, 'destiny', 'hinglish', 'Master Teacher Ka Destiny (Master)',
 'Aapke naam mein 33 ka rare master vibration hai — unconditional love aur compassionate teaching. Aap selfless service aur apne hone ke example se healing karne ke liye ho.',
 '{"Unconditional love","Healing presence","Wisdom","Devotion","Inspirational teaching"}',
 '{"Depletion tak self-sacrifice","Doosron ka bojh uthana","Impossibly high expectations"}',
 '{"Healer","Spiritual leader","Humanitarian","Counselor","Teachers ke teacher"}',
 'Love aapka purpose hai. Aise partners chuno jo aapki depth se match karein aur badle mein aapko replenish karein.',
 'Aapke heart — physical aur emotional — ko nurturing chahiye. Jitni service, utna hi self-love karo.',
 'Aapka path compassion ko embody karna hai, sirf presence se healing karna.');

-- ---------- SOUL URGE ----------
INSERT INTO public.number_meanings (number, category, language, title, purpose, strengths, challenges, careers, relationships, health, spiritual) VALUES
(1, 'soul_urge', 'hinglish', 'Independence Chahne Wala Dil',
 'Gehrai mein aapka dil apne pairon par khade hokar original pehchan chahta hai. Aap tab sabse alive feel karte ho jab lead karte ho ya kuch naya rachte ho. Aapki inner drive sabse aage aur free rehne ki hai.',
 '{"Inner courage","Self-belief","Pioneering desire","Determination"}',
 '{"Approval ki hidden zaroorat","Top par loneliness","Interdependence se bachna"}',
 '{"Leadership","Solo ventures","Creative innovation"}',
 'Aap secretly aisa partner chahte ho jo aapki strength admire kare par barabari se mile. Vulnerability aapki growth hai.',
 'Dabai hui frustration tension banke dikhti hai. Autonomy ki zaroorat ka respect aapko healthy rakhta hai.',
 'Aapki soul seekhti hai ki sachi independence mein doosron ko andar aane dena bhi shaamil hai.'),
(2, 'soul_urge', 'hinglish', 'Harmony Chahne Wala Dil',
 'Aapki gehri ichha peace, closeness aur loving connection ki hai. Aap chahte ho ki aapki zaroorat ho, aap kisi ke ho aur emotional safety feel karo.',
 '{"Emotional depth","Pyaar ki capacity","Sensitivity","Devotion"}',
 '{"Rejection ka dar","People-pleasing","Khud ko khona"}',
 '{"Supportive partnerships","Care work","Mediation"}',
 'Aap deep, secure bonds chahte ho. Aise log chuno jo aapki tenderness ko value karein, exploit na karein.',
 'Emotional turmoil pet aur nerves ko unsettle karta hai. Peace aapke liye literally healing hai.',
 'Aapki soul seekhti hai ki aap khud ko mitaye bina deeply pyaar kar sakte ho.'),
(3, 'soul_urge', 'hinglish', 'Expression Chahne Wala Dil',
 'Aapka inner self rachne, dekha jaane aur joy failane ko tarasta hai. Aap tab fulfilled feel karte ho jab andar ki baat — words, art ya hansi se — express kar pao.',
 '{"Creative chaah","Warmth","Playfulness","Emotional openness"}',
 '{"Constant validation ki zaroorat","Feelings bikherna","Hard emotions se bachna"}',
 '{"Creative arts","Communication","Entertainment"}',
 'Aap aisa partner chahte ho jo aapka celebration kare aur inspire kare. Sparkle ke neeche aap sach mein samjhe jaana chahte ho.',
 'Bottled-up feelings throat aur mood par asar dalti hain. Expression aapka release valve hai.',
 'Aapki soul sirf charm nahi, truth express karna seekhti hai.'),
(4, 'soul_urge', 'hinglish', 'Security Chahne Wala Dil',
 'Gehrai mein aap stability, order aur bharosemand foundation chahte ho. Aap tab peace mein hote ho jab life dependable ho aur mehnat kuch lasting banaye.',
 '{"Loyalty","Steadiness","Inner discipline","Reliability"}',
 '{"Instability ka dar","Insecurity se rigidity","Relax karne mein difficulty"}',
 '{"Structured work","Long-term projects","Stewardship"}',
 'Aap ek steady, faithful partner chahte ho jiske saath life build kar sako. Love ko refuge banne do, ek aur duty nahi.',
 'Worry back aur joints mein basti hai. Life par bharosa grip dheeli karta hai.',
 'Aapki soul seekhti hai ki real security inner hai, sirf bricks ki nahi.'),
(5, 'soul_urge', 'hinglish', 'Freedom Chahne Wala Dil',
 'Aapki gehri ichha freedom, variety aur naye experience ki hai. Aap tab alive feel karte ho jab koi bandhan na ho aur agla adventure khula ho.',
 '{"Life se pyaar","Adaptability","Curiosity","Boldness"}',
 '{"Trapped hone ka dar","Love mein restlessness","Commitment se bachna"}',
 '{"Travel","Dynamic roles","Variety bhara work"}',
 'Aap aisa partner chahte ho jo khud ek adventure ho, anchor nahi. Freedom aur devotion saath reh sakte hain.',
 'Restless energy ko outlets chahiye, warna excess ban jaati hai. Movement aapko steady rakhta hai.',
 'Aapki soul seekhti hai ki sabse deep freedom andar hai, constant escape mein nahi.'),
(6, 'soul_urge', 'hinglish', 'Pyaar Karne Aur Paane Wala Dil',
 'Aapka inner self ek loving ghar, family aur doosron ki care ka mauka chahta hai. Aap tab complete feel karte ho jab apno ke liye nurturing aur harmony rachte ho.',
 '{"Deep caring","Loyalty","Protect karne ki ichha","Sense of beauty"}',
 '{"Over-responsibility","Needed feel karne ki chaah","Self-neglect"}',
 '{"Family-centered work","Healing","Sundar spaces rachna"}',
 'Aap devotion aur shared ghar chahte ho. Dhyan rakho aapka dena saraha jaye, granted na liya jaye.',
 'Aap doosron ka stress dil mein lete ho. Boundaries aapki caregiving ko sustainable banati hain.',
 'Aapki soul pyaar paana utni hi asaani se seekhti hai jitna dena.'),
(7, 'soul_urge', 'hinglish', 'Truth Chahne Wala Dil',
 'Andar gehre aap understanding, solitude aur surface ke neeche ke meaning ko taraste ho. Aap tab fulfilled feel karte ho jab samajh pao ki cheezein sach mein kaise kaam karti hain.',
 '{"Inner depth","Truth se pyaar","Spiritual chaah","Quiet strength"}',
 '{"Emotional guardedness","Hurt hone par withdraw karna","Loneliness"}',
 '{"Research","Spiritual ya analytical work","Specialist depth"}',
 'Aap soul-deep, honest connection chahte ho. Trusted logon ko apni inner walls ke paar aane do.',
 'Mental over-activity neend kharab karti hai. Quiet aur nature aapko restore karte hain.',
 'Aapki soul seekhti hai ki wisdom share karne ke liye hai, chhupane ke liye nahi.'),
(8, 'soul_urge', 'hinglish', 'Achievement Chahne Wala Dil',
 'Aapki gehri ichha success, recognition aur apni duniya ko shape dene ki power ki hai. Aap tab fulfilled feel karte ho jab aapki mehnat real results laye.',
 '{"Ambition","Drive","Resilience","Provide karne ki ichha"}',
 '{"Self-worth ko results se jodna","Hidden insecurity","Rest karne mein difficulty"}',
 '{"Business","Leadership","Wealth building"}',
 'Aap aisa partner chahte ho jo aapki drive respect kare aur saath khada ho. Love ko aisi jagah banne do jahan perform na karna pade.',
 'Pressure heart aur digestion ko target karta hai. Worth output se nahi mapa jaata.',
 'Aapki soul seekhti hai ki fulfillment purpose se aata hai, sirf accumulation se nahi.'),
(9, 'soul_urge', 'hinglish', 'Dene Wala Dil',
 'Gehrai mein aap farak laane, healing karne aur humanity se broadly pyaar karne ko taraste ho. Aap tab complete feel karte ho jab aapki life khud se badi kisi cheez ki seva kare.',
 '{"Compassion","Idealism","Generosity","Emotional wisdom"}',
 '{"Sabko bachana par khud ko nahi","Personal intimacy mein difficulty","Purane dard ko pakde rehna"}',
 '{"Service professions","Message wali arts","Humanitarian roles"}',
 'Aap widely pyaar karte ho; yaad rakho paas khade person ko aapki focused presence bhi chahiye.',
 'Aap duniya ka dukh absorb karte ho. Emotional release aapko healthy rakhta hai.',
 'Aapki soul overflow se dena aur past ko jaane dena seekhti hai.'),
(11, 'soul_urge', 'hinglish', 'Inspire Karne Wala Dil (Master)',
 'Aapka inner self doosron ko uplift aur awaken karne, intuition se jeene aur kisi higher se judne ko tarasta hai. Aap tab fulfilled feel karte ho jab inspire karte ho.',
 '{"Spiritual chaah","Intuitive depth","Idealism","Inspirational warmth"}',
 '{"Nervous sensitivity","Self-doubt","Galat samjhe jaane ka ehsaas"}',
 '{"Inspirational ya healing work","Teaching","Creative-spiritual roles"}',
 'Aap aisa partner chahte ho jo aapki inner world honor kare aur sensitivity ko steady kare.',
 'Aapki fine-tuned nerves ko grounding aur gentle routine chahiye.',
 'Aapki soul apne light par trust karke sensitivity ko service mein badalna seekhti hai.'),
(22, 'soul_urge', 'hinglish', 'Lasting Impact Chahne Wala Dil (Master)',
 'Andar gehre aap kuch aisa banane ko taraste ho jo sach mein matter kare aur bahut logon ki seva kare. Aap tab fulfilled feel karte ho jab grand vision real, lasting good bane.',
 '{"Visionary chaah","Build karne ki drive","Discipline","Scale par seva ki ichha"}',
 '{"Crushing self-expectation","Apne potential ka dar","Overwork"}',
 '{"Large-scale building","Systems aur institutions","Visionary leadership"}',
 'Aap aisa partner chahte ho jo aapke mission mein believe kare aur usme human bane rehne mein madad kare.',
 'Aap jo weight uthate ho use release chahiye — rest luxury nahi, fuel hai.',
 'Aapki soul vast potential ko patient, practical good mein utarna seekhti hai.'),
(33, 'soul_urge', 'hinglish', 'Pyaar Se Healing Karne Wala Dil (Master)',
 'Aapki gehri ichha unconditional pyaar karne aur compassion se doosron ko theek karne ki hai. Aap tab complete feel karte ho jab aapki presence suffer karne walon ko comfort de.',
 '{"Boundless compassion","Healing devotion","Wisdom","Selfless love"}',
 '{"Khali hone tak dena","Sabka dard uthana","Apni needs ki upeksha"}',
 '{"Healing","Spiritual teaching","Compassionate service"}',
 'Love aapke hone ka reason hai. Aise log chuno jo aapko bhi replenish karein jitna aap unke liye behte ho.',
 'Aapke dil ko utni hi care chahiye jitni aap dete ho. Self-compassion essential medicine hai.',
 'Aapki soul seekhti hai ki doosron ki healing khud ko theek karne se shuru hoti hai.');
