-- Phase 1c: AFFIRMATIONS seed (numbers 1-9,11,22,33 x en/hi/hinglish, 3 each)
-- Additive. Safe to re-run.
DELETE FROM public.affirmations WHERE category = 'numerology';
INSERT INTO public.affirmations (number, language, text, category, sort_order) VALUES
(1, 'en', 'I lead my life with courage and clarity.', 'numerology', 1),
(1, 'en', 'I trust my ability to begin and to finish.', 'numerology', 2),
(1, 'en', 'My independence is a strength, not a barrier to love.', 'numerology', 3),
(1, 'hi', 'मैं साहस और स्पष्टता से अपना जीवन चलाता/चलाती हूँ।', 'numerology', 1),
(1, 'hi', 'मैं शुरू करने और पूरा करने की अपनी क्षमता पर भरोसा करता/करती हूँ।', 'numerology', 2),
(1, 'hi', 'मेरी स्वतंत्रता मेरी शक्ति है, प्रेम में बाधा नहीं।', 'numerology', 3),
(1, 'hinglish', 'Main courage aur clarity se apni life lead karta/karti hoon.', 'numerology', 1),
(1, 'hinglish', 'Main shuru karne aur finish karne ki apni ability par trust karta/karti hoon.', 'numerology', 2),
(1, 'hinglish', 'Meri independence meri strength hai, love mein barrier nahi.', 'numerology', 3),
(2, 'en', 'I bring peace and understanding wherever I go.', 'numerology', 1),
(2, 'en', 'My sensitivity is a gift I honor.', 'numerology', 2),
(2, 'en', 'I give love freely while honoring my own needs.', 'numerology', 3),
(2, 'hi', 'मैं जहाँ भी जाता/जाती हूँ, शांति और समझ लाता/लाती हूँ।', 'numerology', 1),
(2, 'hi', 'मेरी संवेदनशीलता एक उपहार है जिसका मैं सम्मान करता/करती हूँ।', 'numerology', 2),
(2, 'hi', 'मैं अपनी ज़रूरतों का सम्मान करते हुए मुक्त रूप से प्रेम देता/देती हूँ।', 'numerology', 3),
(2, 'hinglish', 'Main jahan bhi jaata/jaati hoon, peace aur understanding laata/laati hoon.', 'numerology', 1),
(2, 'hinglish', 'Meri sensitivity ek gift hai jise main honor karta/karti hoon.', 'numerology', 2),
(2, 'hinglish', 'Main apni needs ko honor karte hue freely love deta/deti hoon.', 'numerology', 3),
(3, 'en', 'I express my truth with joy and confidence.', 'numerology', 1),
(3, 'en', 'My creativity flows freely and lifts others.', 'numerology', 2),
(3, 'en', 'I share my light without fear of judgment.', 'numerology', 3),
(3, 'hi', 'मैं अपना सत्य आनंद और आत्मविश्वास से व्यक्त करता/करती हूँ।', 'numerology', 1),
(3, 'hi', 'मेरी रचनात्मकता मुक्त रूप से बहती है और दूसरों को ऊपर उठाती है।', 'numerology', 2),
(3, 'hi', 'मैं बिना निर्णय के डर के अपना प्रकाश बाँटता/बाँटती हूँ।', 'numerology', 3),
(3, 'hinglish', 'Main apna truth joy aur confidence se express karta/karti hoon.', 'numerology', 1),
(3, 'hinglish', 'Meri creativity freely behti hai aur doosron ko uplift karti hai.', 'numerology', 2),
(3, 'hinglish', 'Main judgment ke dar ke bina apna light share karta/karti hoon.', 'numerology', 3),
(4, 'en', 'I build my life on solid, honest foundations.', 'numerology', 1),
(4, 'en', 'My discipline creates lasting security.', 'numerology', 2),
(4, 'en', 'I allow ease and joy alongside my hard work.', 'numerology', 3),
(4, 'hi', 'मैं अपना जीवन मज़बूत, ईमानदार नींव पर बनाता/बनाती हूँ।', 'numerology', 1),
(4, 'hi', 'मेरा अनुशासन स्थायी सुरक्षा रचता है।', 'numerology', 2),
(4, 'hi', 'मैं अपनी मेहनत के साथ सहजता और आनंद को भी आने देता/देती हूँ।', 'numerology', 3),
(4, 'hinglish', 'Main apni life solid, honest foundation par banata/banati hoon.', 'numerology', 1),
(4, 'hinglish', 'Mera discipline lasting security banata hai.', 'numerology', 2),
(4, 'hinglish', 'Main apni mehnat ke saath ease aur joy ko bhi aane deta/deti hoon.', 'numerology', 3),
(5, 'en', 'I embrace change as my path to growth.', 'numerology', 1),
(5, 'en', 'I am free, adaptable, and open to new experiences.', 'numerology', 2),
(5, 'en', 'I find lasting freedom within myself.', 'numerology', 3),
(5, 'hi', 'मैं परिवर्तन को अपनी वृद्धि का मार्ग मानता/मानती हूँ।', 'numerology', 1),
(5, 'hi', 'मैं स्वतंत्र, लचीला/लचीली और नए अनुभवों के लिए खुला/खुली हूँ।', 'numerology', 2),
(5, 'hi', 'मैं अपने भीतर स्थायी स्वतंत्रता पाता/पाती हूँ।', 'numerology', 3),
(5, 'hinglish', 'Main change ko apni growth ka path maanta/maanti hoon.', 'numerology', 1),
(5, 'hinglish', 'Main free, adaptable aur naye experiences ke liye open hoon.', 'numerology', 2),
(5, 'hinglish', 'Main apne andar lasting freedom paata/paati hoon.', 'numerology', 3),
(6, 'en', 'I nurture others from a place of fullness.', 'numerology', 1),
(6, 'en', 'I create harmony and beauty around me.', 'numerology', 2),
(6, 'en', 'I receive love as openly as I give it.', 'numerology', 3),
(6, 'hi', 'मैं पूर्णता से दूसरों का पोषण करता/करती हूँ।', 'numerology', 1),
(6, 'hi', 'मैं अपने चारों ओर सामंजस्य और सौंदर्य रचता/रचती हूँ।', 'numerology', 2),
(6, 'hi', 'मैं प्रेम उतनी ही खुलेपन से पाता/पाती हूँ जितना देता/देती हूँ।', 'numerology', 3),
(6, 'hinglish', 'Main fullness se doosron ko nurture karta/karti hoon.', 'numerology', 1),
(6, 'hinglish', 'Main apne aas-paas harmony aur beauty banata/banati hoon.', 'numerology', 2),
(6, 'hinglish', 'Main love utni hi openness se paata/paati hoon jitna deta/deti hoon.', 'numerology', 3),
(7, 'en', 'I trust my inner wisdom and intuition.', 'numerology', 1),
(7, 'en', 'Solitude restores me; connection enriches me.', 'numerology', 2),
(7, 'en', 'I share my insight to serve others.', 'numerology', 3),
(7, 'hi', 'मैं अपने भीतरी ज्ञान और अंतर्ज्ञान पर भरोसा करता/करती हूँ।', 'numerology', 1),
(7, 'hi', 'एकांत मुझे पुनर्जीवित करता है; जुड़ाव मुझे समृद्ध करता है।', 'numerology', 2),
(7, 'hi', 'मैं अपनी अंतर्दृष्टि दूसरों की सेवा के लिए बाँटता/बाँटती हूँ।', 'numerology', 3),
(7, 'hinglish', 'Main apne inner wisdom aur intuition par trust karta/karti hoon.', 'numerology', 1),
(7, 'hinglish', 'Solitude mujhe restore karta hai; connection mujhe enrich karta hai.', 'numerology', 2),
(7, 'hinglish', 'Main apni insight doosron ki service ke liye share karta/karti hoon.', 'numerology', 3),
(8, 'en', 'I attract abundance through focused effort.', 'numerology', 1),
(8, 'en', 'My worth is not defined by my results.', 'numerology', 2),
(8, 'en', 'I use my power to create good for many.', 'numerology', 3),
(8, 'hi', 'मैं केंद्रित प्रयास से समृद्धि आकर्षित करता/करती हूँ।', 'numerology', 1),
(8, 'hi', 'मेरा मूल्य मेरे परिणामों से परिभाषित नहीं होता।', 'numerology', 2),
(8, 'hi', 'मैं अपनी शक्ति का उपयोग अनेकों के भले के लिए करता/करती हूँ।', 'numerology', 3),
(8, 'hinglish', 'Main focused effort se abundance attract karta/karti hoon.', 'numerology', 1),
(8, 'hinglish', 'Mera worth mere results se define nahi hota.', 'numerology', 2),
(8, 'hinglish', 'Main apni power ka use bahut logon ke bhale ke liye karta/karti hoon.', 'numerology', 3),
(9, 'en', 'I give to the world from a full heart.', 'numerology', 1),
(9, 'en', 'I release what is complete with grace.', 'numerology', 2),
(9, 'en', 'My compassion heals myself and others.', 'numerology', 3),
(9, 'hi', 'मैं भरे हृदय से दुनिया को देता/देती हूँ।', 'numerology', 1),
(9, 'hi', 'जो पूर्ण हो चुका है, उसे मैं कृपा से छोड़ता/छोड़ती हूँ।', 'numerology', 2),
(9, 'hi', 'मेरी करुणा स्वयं को और दूसरों को ठीक करती है।', 'numerology', 3),
(9, 'hinglish', 'Main bhare dil se duniya ko deta/deti hoon.', 'numerology', 1),
(9, 'hinglish', 'Jo complete ho chuka hai use main grace se chhodta/chhodti hoon.', 'numerology', 2),
(9, 'hinglish', 'Meri compassion khud ko aur doosron ko heal karti hai.', 'numerology', 3),
(11, 'en', 'I trust my intuition to light the way.', 'numerology', 1),
(11, 'en', 'My sensitivity is a source of inspiration.', 'numerology', 2),
(11, 'en', 'I stay grounded while reaching for the heights.', 'numerology', 3),
(11, 'hi', 'मैं अपने अंतर्ज्ञान पर भरोसा करता/करती हूँ कि वह राह दिखाएगा।', 'numerology', 1),
(11, 'hi', 'मेरी संवेदनशीलता प्रेरणा का स्रोत है।', 'numerology', 2),
(11, 'hi', 'मैं ऊँचाइयों तक पहुँचते हुए ज़मीन से जुड़ा/जुड़ी रहता/रहती हूँ।', 'numerology', 3),
(11, 'hinglish', 'Main apne intuition par trust karta/karti hoon ki wo raah dikhayega.', 'numerology', 1),
(11, 'hinglish', 'Meri sensitivity inspiration ka source hai.', 'numerology', 2),
(11, 'hinglish', 'Main heights tak pahunchte hue grounded rehta/rehti hoon.', 'numerology', 3),
(22, 'en', 'I turn my vision into lasting reality.', 'numerology', 1),
(22, 'en', 'I build with patience and purpose.', 'numerology', 2),
(22, 'en', 'I trust my power to create meaningful impact.', 'numerology', 3),
(22, 'hi', 'मैं अपनी दृष्टि को स्थायी वास्तविकता में बदलता/बदलती हूँ।', 'numerology', 1),
(22, 'hi', 'मैं धैर्य और उद्देश्य से निर्माण करता/करती हूँ।', 'numerology', 2),
(22, 'hi', 'मैं सार्थक प्रभाव रचने की अपनी शक्ति पर भरोसा करता/करती हूँ।', 'numerology', 3),
(22, 'hinglish', 'Main apni vision ko lasting reality mein badalta/badalti hoon.', 'numerology', 1),
(22, 'hinglish', 'Main patience aur purpose se build karta/karti hoon.', 'numerology', 2),
(22, 'hinglish', 'Main meaningful impact banane ki apni power par trust karta/karti hoon.', 'numerology', 3),
(33, 'en', 'I heal others through unconditional love.', 'numerology', 1),
(33, 'en', 'I serve from compassion, not depletion.', 'numerology', 2),
(33, 'en', 'I care for myself as deeply as I care for others.', 'numerology', 3),
(33, 'hi', 'मैं बिना शर्त प्रेम से दूसरों को ठीक करता/करती हूँ।', 'numerology', 1),
(33, 'hi', 'मैं करुणा से सेवा करता/करती हूँ, थकान से नहीं।', 'numerology', 2),
(33, 'hi', 'मैं अपनी देखभाल उतनी ही गहराई से करता/करती हूँ जितनी दूसरों की।', 'numerology', 3),
(33, 'hinglish', 'Main unconditional love se doosron ko heal karta/karti hoon.', 'numerology', 1),
(33, 'hinglish', 'Main compassion se seva karta/karti hoon, depletion se nahi.', 'numerology', 2),
(33, 'hinglish', 'Main apni care utni hi gehrai se karta/karti hoon jitni doosron ki.', 'numerology', 3);