-- ============================================================
-- Phase 1a: DESTINY number meanings (English)
-- Additive seed for public.number_meanings — category = 'destiny'
-- Numbers: 1-9, 11, 22, 33  | language: en
-- Safe to re-run: deletes only destiny/en rows first, then re-inserts.
-- ============================================================

DELETE FROM public.number_meanings WHERE category = 'destiny' AND language = 'en';

INSERT INTO public.number_meanings (number, category, language, title, purpose, strengths, challenges, careers, relationships, health, spiritual) VALUES
(1, 'destiny', 'en', 'The Pioneer''s Destiny',
 'Your name carries the vibration of leadership and original thought. You are meant to initiate, to stand at the front of new ideas, and to build things that did not exist before you arrived. Your destiny is to become self-reliant and to inspire others to follow their own path.',
 '{"Natural authority","Originality","Drive to achieve","Decisiveness","Self-motivation"}',
 '{"Can seem domineering","Impatience with slower people","Difficulty asking for help"}',
 '{"Founder","Director","Inventor","Department head","Independent consultant"}',
 'You give best in a relationship where your independence is respected. Learn to share decisions rather than dictate them.',
 'Watch tension headaches and high blood pressure that come from carrying everything alone. Movement and delegation protect you.',
 'Your spiritual work is to lead without ego — to use your strength to lift others rather than to dominate them.'),
(2, 'destiny', 'en', 'The Diplomat''s Destiny',
 'Your name vibration is one of partnership, sensitivity, and quiet influence. You are meant to bring people together, to mediate, and to achieve through cooperation rather than force. Your destiny unfolds through relationships and behind-the-scenes contribution.',
 '{"Diplomacy","Deep intuition","Patience","Loyalty","Attention to detail"}',
 '{"Over-sensitivity to criticism","Avoiding conflict to a fault","Self-doubt"}',
 '{"Counselor","Mediator","HR specialist","Designer","Team coordinator"}',
 'You are devoted and tender in love. Guard against losing yourself in your partner — your needs matter equally.',
 'Your nervous system and digestion react to emotional stress. Calm routines and rest keep you balanced.',
 'Your path is to develop inner strength so your gentleness becomes a choice, not a weakness.'),
(3, 'destiny', 'en', 'The Communicator''s Destiny',
 'Your name carries the energy of expression, creativity, and joy. You are meant to communicate — through words, art, performance, or design — and to lift the spirits of those around you. Your destiny is to share your gifts openly with the world.',
 '{"Verbal and artistic talent","Optimism","Charisma","Imagination","Social ease"}',
 '{"Scattering energy across too many things","Avoiding depth","Mood swings"}',
 '{"Writer","Performer","Marketer","Designer","Public speaker"}',
 'You bring laughter and warmth to love, but partners need your focus too — give attention as freely as you give charm.',
 'Throat and skin reflect your emotional state. Creative outlets keep you healthy and grounded.',
 'Your spiritual task is to use your voice for meaning, not just applause.'),
(4, 'destiny', 'en', 'The Builder''s Destiny',
 'Your name vibration is one of structure, discipline, and reliability. You are meant to build solid foundations — in work, family, and society — that outlast you. Your destiny is achieved through steady, honest effort.',
 '{"Discipline","Trustworthiness","Practical skill","Endurance","Loyalty"}',
 '{"Rigidity","Resistance to change","Working to exhaustion"}',
 '{"Engineer","Architect","Operations manager","Accountant","Builder"}',
 'You are a dependable, committed partner. Let warmth and spontaneity in — structure alone can feel cold to loved ones.',
 'Bones, joints, and back carry your stress. Regular rest and stretching are essential.',
 'Your path is to find flexibility within discipline — to build without becoming the prisoner of your own walls.'),
(5, 'destiny', 'en', 'The Explorer''s Destiny',
 'Your name carries the vibration of freedom, change, and adventure. You are meant to experience life widely, to adapt, and to teach others how to embrace change without fear. Your destiny is movement and versatility.',
 '{"Adaptability","Magnetism","Quick thinking","Courage","Versatility"}',
 '{"Restlessness","Difficulty committing","Tendency toward excess"}',
 '{"Travel/hospitality","Sales","Journalism","Entrepreneur","Trainer"}',
 'You need a partner who gives you space and shares your curiosity. Freedom and loyalty can coexist when both are honest.',
 'Your nervous energy needs grounding — guard against addictions and burnout.',
 'Your spiritual work is to find inner freedom, so you stop seeking it only in the next experience.'),
(6, 'destiny', 'en', 'The Nurturer''s Destiny',
 'Your name vibration is one of responsibility, care, and harmony. You are meant to serve family and community, to heal, and to create beauty and balance. Your destiny unfolds through devotion to others.',
 '{"Compassion","Responsibility","Artistic sense","Healing presence","Loyalty"}',
 '{"Over-giving","Worry","Perfectionism toward loved ones"}',
 '{"Teacher","Healthcare","Counselor","Interior designer","Chef"}',
 'You love deeply and protectively. Avoid martyrdom — let others care for you too.',
 'Heart and circulation reflect your emotional load. Boundaries are medicine for you.',
 'Your path is to serve from fullness, not depletion — to balance giving with self-love.'),
(7, 'destiny', 'en', 'The Seeker''s Destiny',
 'Your name carries the vibration of wisdom, analysis, and inner truth. You are meant to study, to understand the hidden nature of things, and to share deep insight. Your destiny is the pursuit of knowledge and spiritual depth.',
 '{"Analytical mind","Intuition","Independence","Depth of thought","Specialist focus"}',
 '{"Isolation","Over-thinking","Difficulty trusting others"}',
 '{"Researcher","Analyst","Scientist","Philosopher","Spiritual teacher"}',
 'You need intellectual and soul connection in love; shallow bonds tire you. Let people into your inner world.',
 'Mental fatigue and sleep are your watch points. Solitude restores you, but isolation drains you.',
 'Your path is to share your wisdom rather than hoard it — to turn solitude into service.'),
(8, 'destiny', 'en', 'The Executive''s Destiny',
 'Your name vibration is one of power, ambition, and material mastery. You are meant to lead enterprises, manage resources, and create abundance — then use it wisely. Your destiny is achievement in the material world.',
 '{"Business instinct","Authority","Resilience","Organization","Vision for scale"}',
 '{"Workaholism","Control issues","Equating worth with money"}',
 '{"Executive","Entrepreneur","Investor","Lawyer","Real estate"}',
 'Respect and shared ambition matter to you in love. Soften — relationships are not deals to be managed.',
 'Stress targets your heart and digestion. Success means little without health to enjoy it.',
 'Your path is to learn that true power is inner — and to use material success for a greater good.'),
(9, 'destiny', 'en', 'The Humanitarian''s Destiny',
 'Your name carries the vibration of compassion, wisdom, and universal service. You are meant to give to humanity, to heal on a wide scale, and to complete cycles with grace. Your destiny is selfless contribution.',
 '{"Compassion","Broad wisdom","Generosity","Artistic depth","Forgiveness"}',
 '{"Emotional overwhelm","Difficulty letting go","Self-sacrifice"}',
 '{"Humanitarian work","Medicine","Teaching","Arts","Counseling"}',
 'You love universally, sometimes at the cost of intimacy. Stay present for the person in front of you.',
 'You absorb others'' pain — emotional boundaries protect your immune system and energy.',
 'Your path is to give without losing yourself, and to release what is complete.'),
(11, 'destiny', 'en', 'The Inspirer''s Destiny (Master)',
 'Your name carries the master vibration of 11 — illumination and spiritual inspiration. You are meant to uplift and awaken others through intuition, vision, and example. Your destiny is to be a light, not merely a leader.',
 '{"Heightened intuition","Inspirational presence","Visionary insight","Sensitivity","Idealism"}',
 '{"Nervous tension","Self-doubt under pressure","Feeling overwhelmed by your own sensitivity"}',
 '{"Spiritual teacher","Artist","Counselor","Visionary founder","Writer"}',
 'You need a partner who understands your sensitivity and supports your mission. Grounding love steadies you.',
 'Your nervous system is finely tuned — grounding practices and rest are essential, not optional.',
 'Your path is to trust your inner light and channel it into service rather than anxiety.'),
(22, 'destiny', 'en', 'The Master Builder''s Destiny (Master)',
 'Your name carries the master vibration of 22 — the power to turn great visions into lasting reality. You are meant to build on a large scale: institutions, movements, or works that serve many. Your destiny is visionary yet deeply practical.',
 '{"Large-scale vision","Practical execution","Leadership","Discipline","Lasting impact"}',
 '{"Immense self-imposed pressure","Self-doubt about your own power","Workaholism"}',
 '{"Large-organization head","Architect","Systems builder","Political/social leader","Innovator"}',
 'You need a grounded partner who supports your mission without competing with it.',
 'The weight of your ambition stresses body and mind — pace yourself, rest is part of the work.',
 'Your path is to ground enormous spiritual potential into practical good for many.'),
(33, 'destiny', 'en', 'The Master Teacher''s Destiny (Master)',
 'Your name carries the rare master vibration of 33 — unconditional love and compassionate teaching. You are meant to heal and uplift through selfless service and the example of your own being. Your destiny is service at the highest level.',
 '{"Unconditional love","Healing presence","Wisdom","Devotion","Inspirational teaching"}',
 '{"Self-sacrifice to depletion","Carrying others'' burdens","Impossibly high self-expectations"}',
 '{"Healer","Spiritual leader","Humanitarian","Counselor","Teacher of teachers"}',
 'Love is your purpose. Choose partners who can match your depth and replenish you in return.',
 'Your heart — physical and emotional — needs nurturing. Practice self-love as fiercely as you serve.',
 'Your path is to embody compassion itself, healing simply through your presence.');
