import jsPDF from 'jspdf';
import type { NumerologyProfile } from './numerology';
import type { VedicProfile } from './vedicNumerology';

interface OnePagerOptions {
  fullName: string;
  dateOfBirth: string;
  profile: NumerologyProfile;
  vedicProfile: VedicProfile;
  archetypeTitle?: string;
  language?: 'en' | 'hi' | 'hinglish';
}

const translations = {
  en: {
    title: 'COSMIC BLUEPRINT SUMMARY',
    subtitle: 'PERSONAL NUMEROLOGY ESSENCE',
    preparedFor: 'Prepared For:',
    dob: 'Date of Birth:',
    archetype: 'Archetype:',
    coreTrinity: 'THE CORE TRINITY',
    mulank: 'Mulank (Birth Number)',
    bhagyank: 'Bhagyank (Destiny Number)',
    naamank: 'Naamank (Name Energy)',
    luckyResonances: 'LUCKY RESONANCES',
    luckyNumbers: 'Lucky Numbers:',
    luckyDays: 'Lucky Days:',
    luckyColors: 'Lucky Colors:',
    luckyDirections: 'Lucky Directions:',
    vedicRemedies: 'VEDIC REMEDIES & ALIGNMENT',
    mantra: 'Mantra:',
    chakra: 'Weak Chakra:',
    chakraTip: 'Chakra Balancing:',
    grah: 'Grah Energy:',
    grahTip: 'Grah Balancing:',
    affirmation: 'DAILY SHIELD & AFFIRMATION',
    footer: 'Generated by AnkJyotish AI • ankjyotishai.com'
  },
  hi: {
    title: 'कॉस्मिक ब्लूप्रिंट सारांश',
    subtitle: 'व्यक्तिगत अंकशास्त्र सार',
    preparedFor: 'तैयार किया गया:',
    dob: 'जन्म तिथि:',
    archetype: 'व्यक्तित्व (Archetype):',
    coreTrinity: 'मुख्य त्रिमूर्ति (The Core Trinity)',
    mulank: 'मूलांक (Birth Number)',
    bhagyank: 'भाग्यांक (Destiny Number)',
    naamank: 'नामांक (Name Energy)',
    luckyResonances: 'शुभ अनुकूलता (Lucky Resonances)',
    luckyNumbers: 'भाग्यशाली अंक:',
    luckyDays: 'भाग्यशाली दिन:',
    luckyColors: 'भाग्यशाली रंग:',
    luckyDirections: 'भाग्यशाली दिशाएं:',
    vedicRemedies: 'वैदिक उपाय और संरेखण',
    mantra: 'मंत्र:',
    chakra: 'कमजोर चक्र:',
    chakraTip: 'चक्र संतुलन:',
    grah: 'ग्रह ऊर्जा:',
    grahTip: 'ग्रह संतुलन:',
    affirmation: 'दैनिक प्रतिज्ञान (Daily Affirmation)',
    footer: 'अंकज्योतिष एआई द्वारा जनरेटेड • ankjyotishai.com'
  },
  hinglish: {
    title: 'COSMIC BLUEPRINT SUMMARY',
    subtitle: 'PERSONAL NUMEROLOGY KA ESSENCE',
    preparedFor: 'Prepared For:',
    dob: 'Birth Date:',
    archetype: 'Archetype:',
    coreTrinity: 'CORE TRINITY (Mulank, Bhagyank, Naamank)',
    mulank: 'Mulank (Birth Number)',
    bhagyank: 'Bhagyank (Destiny Number)',
    naamank: 'Naamank (Name Energy)',
    luckyResonances: 'LUCKY RESONANCES (Shubh Attributes)',
    luckyNumbers: 'Lucky Numbers:',
    luckyDays: 'Lucky Days:',
    luckyColors: 'Lucky Colors:',
    luckyDirections: 'Lucky Directions:',
    vedicRemedies: 'VEDIC REMEDIES & ALIGNMENT',
    mantra: 'Mantra:',
    chakra: 'Weak Chakra:',
    chakraTip: 'Chakra Balancing:',
    grah: 'Grah Energy:',
    grahTip: 'Grah Balancing:',
    affirmation: 'DAILY SHIELD & AFFIRMATION',
    footer: 'Generated by AnkJyotish AI • ankjyotishai.com'
  }
};

const affirmationsDict: Record<number, string[]> = {
  1: [
    "I am a natural pioneer, leading my life with courage and clarity.",
    "My independence is my strength, and I walk my path with confidence."
  ],
  2: [
    "I bring peace, harmony, and cooperative balance to everyone around me.",
    "My intuition is my guidance, and I trust the flow of my relationships."
  ],
  3: [
    "I express my creativity and joy freely and inspire others to do the same.",
    "My communication is clear, positive, and uplifts the spirits of others."
  ],
  4: [
    "I build stable, long-lasting foundations with discipline and order.",
    "My focus and dedication bring security and peace to my endeavors."
  ],
  5: [
    "I embrace change, adaptability, and positive freedom in all areas.",
    "I learn from every experience and welcome exciting new opportunities."
  ],
  6: [
    "I nurture my loved ones and create a harmonious, beautiful environment.",
    "I balance responsibility with self-love, knowing my heart is my compass."
  ],
  7: [
    "I trust my inner wisdom and connect deeply with spiritual truths.",
    "Solitude brings me strength, and clarity guides my path of seeking."
  ],
  8: [
    "I manifest material and spiritual abundance with wisdom and power.",
    "My authority is rooted in ethical action and generosity for all."
  ],
  9: [
    "I embody universal love and complete cycles with grace and wisdom.",
    "My life is in service of humanity, and I release what no longer serves me."
  ]
};

export const generateOnePagerPDF = async ({
  fullName,
  dateOfBirth,
  profile,
  vedicProfile,
  archetypeTitle = 'Seeker',
  language = 'en'
}: OnePagerOptions): Promise<void> => {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const lang = language as 'en' | 'hi' | 'hinglish';
  const L = translations[lang] || translations.en;

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);

  // Set premium Royal Aura deep background
  doc.setFillColor(18, 10, 36);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Draw double borders in Gold
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.3);
  doc.rect(8, 8, pageWidth - 16, pageHeight - 16);
  doc.setLineWidth(0.6);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);

  // Draw corner ornaments
  const corners = [
    { x: 10, y: 10 },
    { x: pageWidth - 10, y: 10 },
    { x: 10, y: pageHeight - 10 },
    { x: pageWidth - 10, y: pageHeight - 10 }
  ];
  doc.setLineWidth(0.5);
  corners.forEach((c) => {
    // draw small corner crosses
    doc.line(c.x - 3, c.y, c.x + 3, c.y);
    doc.line(c.x, c.y - 3, c.x, c.y + 3);
  });

  let y = 20;

  // Header Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(212, 175, 55);
  doc.text('ANKJYOTISH AI', pageWidth / 2, y, { align: 'center' });
  y += 6;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(199, 184, 230);
  doc.text(L.subtitle, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Horizontal divider
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.5);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;

  // Prepared For panel
  doc.setFillColor(32, 18, 58);
  doc.roundedRect(margin, y, contentWidth, 22, 2, 2, 'F');
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(212, 175, 55);
  doc.text(L.preparedFor, margin + 6, y + 8);
  doc.text(L.dob, margin + 95, y + 8);
  doc.text(L.archetype, margin + 140, y + 8);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(fullName.toUpperCase(), margin + 6, y + 15);
  doc.text(dateOfBirth, margin + 95, y + 15);
  doc.text(archetypeTitle, margin + 140, y + 15);
  
  y += 32;

  // Section: The Core Trinity
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(212, 175, 55);
  doc.text(L.coreTrinity, margin, y);
  y += 5;

  // Columns for Mulank, Bhagyank, Naamank
  const colWidth = 56;
  const colSpacing = 6;
  const trinity = [
    { label: L.mulank, val: String(profile.lifePath), desc: lang === 'hi' ? 'आपका मूल स्वभाव और प्राकृतिक गुण।' : 'Represents your core personality & talents.' },
    { label: L.bhagyank, val: String(profile.destiny), desc: lang === 'hi' ? 'आपकी जीवन दिशा और अंतिम भाग्य।' : 'Defines your destiny and path in this lifetime.' },
    { label: L.naamank, val: String(profile.personality), desc: lang === 'hi' ? 'आपके नाम की ऊर्जा और चुंबकीय प्रभाव।' : 'Your public vibration and cosmic projection.' }
  ];

  trinity.forEach((item, idx) => {
    const x = margin + idx * (colWidth + colSpacing);
    // Draw card background
    doc.setFillColor(32, 18, 58);
    doc.roundedRect(x, y, colWidth, 40, 3, 3, 'F');
    // Draw thin gold card border
    doc.setDrawColor(212, 175, 55);
    doc.setLineWidth(0.3);
    doc.rect(x, y, colWidth, 40);

    // Label
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    doc.setTextColor(199, 184, 230);
    doc.text(item.label, x + colWidth / 2, y + 8, { align: 'center' });

    // Huge Number
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(28);
    doc.setTextColor(212, 175, 55);
    doc.text(item.val, x + colWidth / 2, y + 22, { align: 'center' });

    // Description text wrapping
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.setTextColor(255, 255, 255);
    const descLines = doc.splitTextToSize(item.desc, colWidth - 8);
    doc.text(descLines, x + 4, y + 29);
  });

  y += 48;

  // Two Column Section: Lucky Resonances (Left) vs Vedic Alignment (Right)
  const halfColWidth = (contentWidth - 6) / 2;
  
  // Left: Lucky Resonances
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(212, 175, 55);
  doc.text(L.luckyResonances, margin, y);

  // Right: Vedic Alignment
  doc.text(L.vedicRemedies, margin + halfColWidth + 6, y);

  y += 5;

  // Left card background
  doc.setFillColor(32, 18, 58);
  doc.roundedRect(margin, y, halfColWidth, 54, 3, 3, 'F');
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.3);
  doc.rect(margin, y, halfColWidth, 54);

  // Right card background
  doc.roundedRect(margin + halfColWidth + 6, y, halfColWidth, 54, 3, 3, 'F');
  doc.rect(margin + halfColWidth + 6, y, halfColWidth, 54);

  // Fill Left Card (Lucky Attributes)
  const leftX = margin + 6;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(199, 184, 230);
  
  doc.text(L.luckyNumbers, leftX, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(profile.luckyAttributes.numbers.join(', '), leftX, y + 15);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(199, 184, 230);
  doc.text(L.luckyDays, leftX, y + 22);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(profile.luckyAttributes.days.join(', '), leftX, y + 27);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(199, 184, 230);
  doc.text(L.luckyColors, leftX, y + 34);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(profile.luckyAttributes.colors.join(', '), leftX, y + 39);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(199, 184, 230);
  doc.text(L.luckyDirections, leftX, y + 46);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(profile.luckyAttributes.directions.join(', '), leftX, y + 50);

  // Fill Right Card (Vedic Remedies)
  const rightX = margin + halfColWidth + 12;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(199, 184, 230);
  
  doc.text(L.mantra, rightX, y + 10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  const mantraText = doc.splitTextToSize(vedicProfile.remedies.personalMantra, halfColWidth - 12);
  doc.text(mantraText, rightX, y + 14);

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(199, 184, 230);
  doc.text(L.chakra, rightX, y + 24);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(`${vedicProfile.remedies.weakChakra} - ${L.chakraTip} ${vedicProfile.remedies.chakraBalancingTip.split('.')[0]}.`, rightX, y + 28, { maxWidth: halfColWidth - 12 });

  doc.setFont('helvetica', 'bold');
  doc.setTextColor(199, 184, 230);
  doc.text(L.grah, rightX, y + 40);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  doc.text(vedicProfile.remedies.grahEnergy, rightX, y + 44, { maxWidth: halfColWidth - 12 });

  y += 62;

  // Affirmations Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(212, 175, 55);
  doc.text(L.affirmation, margin, y);
  y += 5;

  doc.setFillColor(32, 18, 58);
  doc.roundedRect(margin, y, contentWidth, 34, 3, 3, 'F');
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.3);
  doc.rect(margin, y, contentWidth, 34);

  const mSingle = profile.lifePath > 9 ? (profile.lifePath === 11 ? 2 : profile.lifePath === 22 ? 4 : 6) : profile.lifePath;
  const affs = affirmationsDict[mSingle] || affirmationsDict[1];
  
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9.5);
  doc.setTextColor(255, 255, 255);
  
  doc.text(`1. "${affs[0]}"`, margin + 6, y + 11, { maxWidth: contentWidth - 12 });
  doc.text(`2. "${affs[1]}"`, margin + 6, y + 23, { maxWidth: contentWidth - 12 });

  y += 43;

  // General Disclaimer / Note
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(199, 184, 230);
  const note = lang === 'hi' 
    ? "यह रिपोर्ट अंकज्योतिषीय गणनाओं पर आधारित है। अंक हमारे जीवन की प्रवृत्तियों को दर्शाते हैं, भाग्य को कठोरता से तय नहीं करते। अपनी सकारात्मक ऊर्जा पर विश्वास रखें।"
    : "This report outlines numerical vibrations representing potentials and tendencies. Energy responds to conscious awareness and deliberate intent. Use this blueprint to guide your choices.";
  const noteLines = doc.splitTextToSize(note, contentWidth);
  doc.text(noteLines, margin, y);

  // Footer
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8.5);
  doc.setTextColor(212, 175, 55);
  doc.text(L.footer, pageWidth / 2, pageHeight - 14, { align: 'center' });

  // Save the PDF
  doc.save(`${fullName.replace(/\s+/g, '_')}_Cosmic_Blueprint.pdf`);
};
