import jsPDF from 'jspdf';
import type { UserFormData } from '@/types/formTypes';
import { type NumerologyProfile, numberMeanings, reduceToSingleDigit, calculateLifePath, calculateCompatibility, calculateDestiny, calculateSoulUrge } from '@/lib/numerology';
import { correctName } from '@/lib/nameCorrection';
import { analyzeVehicle, analyzeHouse } from '@/lib/vehicleHouseVibration';
import { calculateBusinessVibration, suggestBrandTweaks } from '@/lib/businessNameVibration';
import { REMEDIES } from '@/lib/remedies';

// ---------------------------------------------------------------------
// Branding (from app_branding table). All optional — safe fallbacks.
// ---------------------------------------------------------------------
export interface Branding {
  company_name?: string;
  logo_url?: string;
  brand_color?: string;
  accent_color?: string;
  tagline?: string;
  footer_text?: string;
  contact_line?: string;
  website?: string;
}

const DEFAULT_BRANDING: Required<Branding> = {
  company_name: 'AnkJyotish AI',
  logo_url: '',
  brand_color: '#7c3aed',
  accent_color: '#f0a500',
  tagline: 'Numerology that changes lives',
  footer_text: 'Generated by AnkJyotish AI • ankjyotishai.com',
  contact_line: '',
  website: 'ankjyotishai.com',
};

export type ReportKey =
  | 'name_correction' | 'mobile_numerology' | 'vehicle_numerology'
  | 'career_numerology' | 'baby_name' | 'compatibility_report'
  | 'business_numerology' | 'property_numerology' | 'marriage_report'
  | 'shani_sade_sati' | 'pitra_dosh_karmic' | 'wealth_yogas_kundli'
  | 'health_vitality_kundli' | 'foreign_settlement_travel' | 'mangal_dosha_analysis'
  | 'full_blueprint';

const REPORT_TITLES: Record<ReportKey, string> = {
  name_correction: 'Name Correction Report',
  mobile_numerology: 'Mobile Number Numerology',
  vehicle_numerology: 'Vehicle Number Report',
  career_numerology: 'Career & 10th House Karma Report',
  baby_name: 'Lucky Baby Name Selection Report',
  compatibility_report: 'Love & Relationship Compatibility',
  business_numerology: 'Business & Brand Numerology Report',
  property_numerology: 'Property & House Number Report',
  marriage_report: 'Marriage Timing & 36-Gun Milan Report',
  shani_sade_sati: 'Shani Sade Sati & Dhaiya Remedial Blueprint',
  pitra_dosh_karmic: 'Pitra Dosh & Ancestral Karma Report',
  wealth_yogas_kundli: 'Dhana Yogas & Laxmi Prapti Blueprint',
  health_vitality_kundli: 'Medical Astrology & Vitality Blueprint',
  foreign_settlement_travel: 'Foreign Settlement & PR Immigration Report',
  mangal_dosha_analysis: 'Complete Manglik Dosha & Remedies Report',
  full_blueprint: 'Personal Numerology & Kundli Blueprint',
};

// hex -> [r,g,b]
const hex = (h: string): [number, number, number] => {
  const m = (h || '').replace('#', '');
  const v = m.length === 3 ? m.split('').map((c) => c + c).join('') : m;
  const n = parseInt(v || '7c3aed', 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
};

// load logo: data URL used directly, else fetched (best-effort)
const loadLogo = async (url: string): Promise<string | null> => {
  if (!url) return null;
  if (url.startsWith('data:')) return url; // uploaded logo (base64) — use as-is
  try {
    const res = await fetch(url, { mode: 'cors' });
    const blob = await res.blob();
    return await new Promise((resolve) => {
      const r = new FileReader();
      r.onloadend = () => resolve(typeof r.result === 'string' ? r.result : null);
      r.onerror = () => resolve(null);
      r.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
};

const logoFormat = (data: string): 'PNG' | 'JPEG' | 'WEBP' => {
  if (data.includes('image/jpeg') || data.includes('image/jpg')) return 'JPEG';
  if (data.includes('image/webp')) return 'WEBP';
  return 'PNG';
};

const RULING_PLANETS: Record<number, string> = {
  1: 'Sun (Surya)',
  2: 'Moon (Chandra)',
  3: 'Jupiter (Guru)',
  4: 'Rahu',
  5: 'Mercury (Budh)',
  6: 'Venus (Shukra)',
  7: 'Ketu',
  8: 'Saturn (Shani)',
  9: 'Mars (Mangal)',
};

const getLifePathFromAnyDobFormat = (dob: string): number => {
  if (!dob) return 0;
  try {
    let parts: string[] = [];
    if (dob.includes('-')) {
      parts = dob.split('-');
    } else if (dob.includes('/')) {
      parts = dob.split('/');
    }
    if (parts.length === 3) {
      if (parts[0].length === 4) {
        const y = Number(parts[0]);
        const m = Number(parts[1]);
        const d = Number(parts[2]);
        return calculateLifePath(`${String(d).padStart(2, '0')}/${String(m).padStart(2, '0')}/${y}`);
      } else {
        return calculateLifePath(dob);
      }
    }
  } catch (err) {
    console.error('getLifePathFromAnyDobFormat error', err);
  }
  return 1;
};

const getMulankFromAnyDobFormat = (dob: string): number => {
  if (!dob) return 0;
  try {
    let parts: string[] = [];
    if (dob.includes('-')) {
      parts = dob.split('-');
    } else if (dob.includes('/')) {
      parts = dob.split('/');
    }
    if (parts.length === 3) {
      let d = 1;
      if (parts[0].length === 4) {
        d = Number(parts[2]);
      } else {
        d = Number(parts[0]);
      }
      if (d === 11 || d === 22) return d;
      return reduceToSingleDigit(d, false);
    }
  } catch (err) {
    console.error('getMulankFromAnyDobFormat error', err);
  }
  return 1;
};

const calculatePersonalYearForYear = (dob: string, year: number): number => {
  try {
    let day = 1, month = 1;
    let parts: string[] = [];
    if (dob.includes('-')) {
      parts = dob.split('-');
      if (parts[0].length === 4) {
        day = Number(parts[2]);
        month = Number(parts[1]);
      } else {
        day = Number(parts[0]);
        month = Number(parts[1]);
      }
    } else if (dob.includes('/')) {
      parts = dob.split('/');
      day = Number(parts[0]);
      month = Number(parts[1]);
    }
    
    const daySum = String(day).split('').reduce((sum, d) => sum + parseInt(d), 0);
    const monthSum = String(month).split('').reduce((sum, d) => sum + parseInt(d), 0);
    const yearSum = String(year).split('').reduce((sum, d) => sum + parseInt(d), 0);
    
    const total = daySum + monthSum + yearSum;
    const sumDigits = (n: number): number => String(n).split('').reduce((acc, char) => acc + (Number(char) || 0), 0);
    const reduce = (n: number): number => (n <= 9 ? n : reduce(sumDigits(n)));
    return reduce(total);
  } catch {
    return 1;
  }
};

// ---------------------------------------------------------------------
// Main: generate a branded, per-report-type PDF
// ---------------------------------------------------------------------
export interface AiContent {
  summary?: string;
  strengths?: string[];
  risks?: string[];
  actions?: string[];
  luckyFocus?: string;
  timeline?: string;
  closingNote?: string;
}
export interface PdfOptions {
  tier?: 'free' | 'paid';      // free = 1-page teaser + upsell
  upsellPrice?: number;        // this report's paid price (e.g. 299)
  masterPrice?: number;        // master plan price (e.g. 999)
  aiContent?: AiContent | null; // personalized AI content (paid)
  nikbContext?: any;           // NIKB detailed database parameters
  babyNames?: any[] | null;    // baby names list fetched from DB
  language?: 'en' | 'hi' | 'hinglish';
}
export const generateWhiteLabelPDF = async (
  reportKey: ReportKey,
  formData: UserFormData,
  profile: NumerologyProfile,
  branding?: Branding,
  opts?: PdfOptions,
): Promise<void> => {
  const activeLang = opts?.language || 'en';
  const tier = opts?.tier || 'paid';
  const upsellPrice = opts?.upsellPrice || 299;
  const masterPrice = opts?.masterPrice || 999;

  let babyNamesList = opts?.babyNames || null;
  if (reportKey === 'baby_name' && !babyNamesList) {
    try {
      const { supabase } = await import('@/integrations/supabase/client');
      const babyGender = (formData as any).babyGender || 'unisex';
      const preferredLetter = (formData as any).preferredLetter || '';
      const babyDob = formData.dateOfBirth;
      
      let luckyRoot = 1;
      if (babyDob) {
        const parts = babyDob.split(/[-\/]/);
        const d = parts[0].length === 4 ? Number(parts[2]) : Number(parts[0]);
        const sumDigits = (n: number): number => String(n).split('').reduce((acc, char) => acc + (Number(char) || 0), 0);
        const reduce = (n: number): number => (n <= 9 ? n : reduce(sumDigits(n)));
        luckyRoot = reduce(sumDigits(d));
      } else {
        luckyRoot = profile.birthday || 1;
      }

      let q = supabase.from('baby_names').select('*').eq('name_root', luckyRoot);
      if (babyGender && babyGender !== 'any') {
        q = q.eq('gender', babyGender);
      }
      if (preferredLetter) {
        q = q.eq('first_letter', preferredLetter.toUpperCase());
      }
      const { data: names } = await q.limit(15);
      if (names && names.length > 0) {
        babyNamesList = names;
      }
    } catch (err) {
      console.error('Failed to auto-fetch baby names inside PDF gen', err);
    }
  }
  const b = { ...DEFAULT_BRANDING, ...(branding || {}) };
  const brand = hex(b.brand_color);
  const accent = hex(b.accent_color);
  const ink: [number, number, number] = [40, 35, 55];
  const soft: [number, number, number] = [110, 105, 125];

  const doc = new jsPDF();
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 18;
  const CW = W - M * 2;
  let y = M;
  let pageNo = 0;

  const logoData = await loadLogo(b.logo_url);

  const REPORT_FOLDERS: Record<ReportKey, string> = {
    name_correction: 'name-correction',
    mobile_numerology: 'mobile-numerology',
    vehicle_numerology: 'vehicle-numerology',
    career_numerology: 'career-numerology',
    baby_name: 'baby-name',
    compatibility_report: 'compatibility',
    business_numerology: 'business',
    property_numerology: 'property',
    marriage_report: 'marriage',
    full_blueprint: 'generic',
  };
  const folder = REPORT_FOLDERS[reportKey];
  const bannerPath = folder && folder !== 'generic' ? `/images/reports/${folder}/banner.jpg` : '/images/reports/generic_banner.jpg';
  const fullBannerUrl = `${window.location.origin}${bannerPath}`;
  const bannerData = await loadLogo(fullBannerUrl) || await loadLogo(`${window.location.origin}/images/reports/generic_banner.jpg`);

  // ---- header band (every page) ----
  const header = () => {
    doc.setFillColor(...brand);
    doc.rect(0, 0, W, 22, 'F');
    if (logoData) {
      try { doc.addImage(logoData, logoFormat(logoData), M, 5, 12, 12); } catch { /* ignore */ }
    }
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.text(b.company_name, logoData ? M + 16 : M, 14);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...accent);
    doc.text(b.website, W - M, 14, { align: 'right' });
    y = 32;
  };

  // ---- footer (every page) ----
  const footer = () => {
    doc.setDrawColor(...accent);
    doc.setLineWidth(0.4);
    doc.line(M, H - 18, W - M, H - 18);
    doc.setTextColor(...soft);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7.5);
    doc.text(b.footer_text, M, H - 12);
    if (b.contact_line) doc.text(b.contact_line, M, H - 7);
    doc.text(String(pageNo), W - M, H - 12, { align: 'right' });
  };

  const newPage = (first = false) => {
    if (!first) doc.addPage();
    pageNo += 1;
    doc.setFillColor(252, 251, 254);
    doc.rect(0, 0, W, H, 'F');
    header();
    footer();
  };

  const ensure = (need: number) => { if (y + need > H - 24) { newPage(); } };

  let sectionNo = 0;
  const resetSections = () => { sectionNo = 0; };
  const h2 = (t: string, numbered = true) => {
    ensure(20);
    if (numbered) {
      sectionNo += 1;
      const tag = String(sectionNo).padStart(2, '0');
      // number badge
      doc.setFillColor(brand[0], brand[1], brand[2]);
      doc.setGState(new (doc as any).GState({ opacity: 0.1 }));
      doc.roundedRect(M, y - 5, 13, 9, 1.5, 1.5, 'F');
      doc.setGState(new (doc as any).GState({ opacity: 1 }));
      doc.setTextColor(...brand);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text(tag, M + 6.5, y + 1.2, { align: 'center' });
      doc.setTextColor(...brand);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14.5);
      doc.text(t, M + 18, y);
      y += 6;
      doc.setDrawColor(...accent);
      doc.setLineWidth(0.8);
      doc.line(M + 18, y, M + 46, y);
      y += 9;
    } else {
      doc.setTextColor(...brand);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(14.5);
      doc.text(t, M, y);
      y += 6;
      doc.setDrawColor(...accent);
      doc.setLineWidth(0.8);
      doc.line(M, y, M + 28, y);
      y += 9;
    }
  };

  const para = (t: string, size = 10.5) => {
    doc.setTextColor(...ink);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(t, CW);
    lines.forEach((ln: string) => { ensure(7); doc.text(ln, M, y); y += size * 0.55; });
    y += 4;
  };

  const chip = (label: string, value: string) => {
    ensure(16);
    doc.setFillColor(brand[0], brand[1], brand[2]);
    doc.setGState(new (doc as any).GState({ opacity: 0.08 }));
    doc.roundedRect(M, y - 4, CW, 13, 2, 2, 'F');
    doc.setGState(new (doc as any).GState({ opacity: 1 }));
    doc.setTextColor(...soft);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(label, M + 4, y + 4);
    doc.setTextColor(...brand);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(value, W - M - 4, y + 4, { align: 'right' });
    y += 16;
  };

  const bullets = (items: string[]) => {
    items.forEach((it) => {
      ensure(8);
      doc.setTextColor(...accent);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10.5);
      doc.text('•', M, y);
      doc.setTextColor(...ink);
      doc.setFont('helvetica', 'normal');
      const lines = doc.splitTextToSize(it, CW - 6);
      lines.forEach((ln: string, i: number) => { if (i) ensure(6); doc.text(ln, M + 5, y); y += 5.8; });
      y += 1.5;
    });
    y += 3;
  };

  // =================== COVER ===================
  newPage(true);
  doc.setFillColor(...brand);
  doc.rect(0, 22, W, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(26);
  doc.text(REPORT_TITLES[reportKey], W / 2, 55, { align: 'center', maxWidth: CW });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(...accent);
  doc.text(b.tagline, W / 2, 70, { align: 'center' });

  if (bannerData) {
    try {
      doc.addImage(bannerData, logoFormat(bannerData), 35, 94, 140, 70);
    } catch (err) {
      console.warn('[pdf] banner render failed:', err);
    }
  }

  y = bannerData ? 176 : 110;
  const who = formData.displayName || formData.fullBirthName || 'Valued Seeker';
  doc.setTextColor(...soft);
  doc.setFontSize(10);
  doc.text('PREPARED EXCLUSIVELY FOR', W / 2, y, { align: 'center' });
  y += 10;
  doc.setTextColor(...ink);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text(who.toUpperCase(), W / 2, y, { align: 'center' });
  y += 12;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...soft);
  if (formData.dateOfBirth) { doc.text(`Date of Birth: ${formData.dateOfBirth}`, W / 2, y, { align: 'center' }); y += 7; }
  doc.text(`Report Date: ${new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}`, W / 2, y, { align: 'center' });

  // core numbers strip on cover
  y = bannerData ? 226 : 168;
  const core = [
    { l: 'Mulank', v: String(profile.birthday) },
    { l: 'Bhagyank', v: String(profile.lifePath) },
    { l: 'Namaank', v: String(profile.destiny) },
  ];
  const bw = (CW - 8) / 3;
  core.forEach((c, i) => {
    const x = M + i * (bw + 4);
    doc.setFillColor(...brand);
    doc.setGState(new (doc as any).GState({ opacity: 0.06 }));
    doc.roundedRect(x, y, bw, 30, 3, 3, 'F');
    doc.setGState(new (doc as any).GState({ opacity: 1 }));
    doc.setTextColor(...brand);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(24);
    doc.text(c.v, x + bw / 2, y + 16, { align: 'center' });
    doc.setTextColor(...soft);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(c.l, x + bw / 2, y + 25, { align: 'center' });
  });

  // =================== CONTENT (per report) ===================
  newPage();
  const lp = numberMeanings[profile.birthday] || numberMeanings[reduceToSingleDigit(profile.birthday, false)] || numberMeanings[9];
  const dest = numberMeanings[profile.destiny] || numberMeanings[9];
  const lucky = profile.luckyAttributes;

  let remedyList = null;
  try {
    const { supabase } = await import('@/integrations/supabase/client');
    const { data: dbRem } = await supabase
      .from('remedies')
      .select('*')
      .eq('number', reduceToSingleDigit(profile.birthday, false))
      .maybeSingle();
    if (dbRem) {
      remedyList = {
        number: dbRem.number,
        planet: dbRem.planet_en,
        color: { en: dbRem.color_en, hi: dbRem.color_hi || dbRem.color_en },
        day: dbRem.day_en,
        gemstone: { en: dbRem.gemstone_en, hi: dbRem.gemstone_hi || dbRem.gemstone_en },
        mantra: dbRem.mantra,
        remedies: {
          en: dbRem.remedies_en,
          hi: dbRem.remedies_hi,
          hinglish: dbRem.remedies_hinglish
        }
      };
    }
  } catch (err) {
    console.error('Failed to load database remedies inside PDF gen:', err);
  }

  const remedy = remedyList || REMEDIES[profile.birthday] || REMEDIES[reduceToSingleDigit(profile.birthday, false)];

  // ---------- FREE 1-PAGE TEASER + UPSELL ----------
  if (tier === 'free') {
    h2('Your Free Snapshot');
    para(`Aapka Mulank ${profile.birthday} ("${lp.title}") hai. ${lp.purpose.split('. ').slice(0, 2).join('. ')}.`);
    chip('Lucky Numbers', lucky.numbers.slice(0, 3).join(', '));
    chip('Lucky Colours', lucky.colors.join(', '));
    chip('Lucky Days', lucky.days.join(', '));

    // locked teaser list
    h2('Aapki Full Report Mein Kya Milega');
    const lockedItems: Record<string, string[]> = {
      name_correction: ['Aapke naam ki sahi spelling (3-5 options)', 'Har spelling ka success match %', 'Lucky signature style', 'Personalised remedies'],
      mobile_numerology: ['Aapke number ka pura vibration', 'Lucky vs unlucky digits', 'Best number suggestion', 'Money & career impact'],
      vehicle_numerology: ['Vehicle number safety/luck/harmony score', 'Accident-prone digits check', 'Lucky plate suggestion', 'Remedies'],
      career_numerology: ['Aapke liye best 5 careers', 'Job vs business analysis', 'Lucky career timing', 'Strength-weakness map'],
      baby_name: ['10+ auspicious naam options', 'Har naam ka numerology score', 'Shubh naamkaran date', 'Lucky rashi alignment'],
      compatibility_report: ['Partner ke saath full match %', 'Strength & risk areas', 'Marriage timing guidance', 'Remedies for harmony'],
      full_blueprint: ['100+ page deep analysis', 'Life cycles & predictions', 'Loshu grid & remedies', 'Year-by-year forecast'],
    };
    bullets((lockedItems[reportKey] || lockedItems.full_blueprint).map((x) => x + '  🔒'));

    // big upsell box
    ensure(60);
    doc.setFillColor(...brand);
    doc.roundedRect(M, y, CW, 52, 4, 4, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(15);
    doc.text('Unlock Your Full Personalised Report', W / 2, y + 13, { align: 'center' });
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(...accent);
    doc.text(`Sirf is report ke liye: Rs.${upsellPrice}`, W / 2, y + 25, { align: 'center' });
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.text(`Ya sab kuch ek saath — Master Plan Rs.${masterPrice} (saari reports + AI chat)`, W / 2, y + 35, { align: 'center' });
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(...accent);
    doc.text(`Visit ${b.website} to upgrade`, W / 2, y + 45, { align: 'center' });
    y += 60;

    doc.save(`${REPORT_TITLES[reportKey].replace(/[^a-z0-9]/gi, '_')}_FREE_${(formData.displayName || formData.fullBirthName || 'report').replace(/[^a-z0-9]/gi, '_')}.pdf`);
    return;
  }

  // ---------- PAID FULL REPORT ----------
  // intro common
  const bp = numberMeanings[profile.lifePath] || numberMeanings[reduceToSingleDigit(profile.lifePath, false)] || numberMeanings[9];
  h2('Your Core Energy');
  para(`Aapka Mulank (Birth Number) ${profile.birthday} hai — "${lp.title}". ${lp.purpose}`);
  para(`Aapka Bhagyank (Destiny Number) ${profile.lifePath} hai — "${bp.title}". ${bp.purpose}`);
  chip('Lucky Numbers', lucky.numbers.join(', '));
  chip('Lucky Colours', lucky.colors.join(', '));
  chip('Lucky Days', lucky.days.join(', '));

  switch (reportKey) {
    case 'name_correction': {
      const res = correctName(formData.fullBirthName || who, profile.birthday);
      // Print analyzed name
      chip(activeLang === 'hi' ? 'विश्लेषण किया गया नाम' : activeLang === 'hinglish' ? 'Analyzed Name' : 'Analyzed Name', formData.fullBirthName || who);
      
      h2(activeLang === 'hi' ? 'नाम सुधार विश्लेषण' : activeLang === 'hinglish' ? 'Name Correction Analysis' : 'Name Correction Analysis');
      
      let introText = '';
      if (activeLang === 'hi') {
        introText = `आपके वर्तमान नाम का अंकशास्त्र कंपन मूल ${res.originalRoot} है। ${res.alreadyGood ? 'आपका नाम पहले से ही आपके मूलांक के साथ पूर्ण अनुकूलता में है - किसी सुधार की आवश्यकता नहीं है।' : 'यह कंपन आपके मूलांक के साथ पूर्णतः अनुकूल नहीं है। बेहतर परिणामों के लिए नीचे कुछ विकल्प दिए गए हैं।'}`;
      } else if (activeLang === 'hinglish') {
        introText = `Aapke current naam ka root number ${res.originalRoot} hai. ${res.alreadyGood ? 'Aapka naam pehle se hi aapke Mulaank ke saath harmony mein hai — minor tuning se aur strong ho sakta hai.' : 'Niche kuch spelling options diye gaye hain jo aapke birth number (Mulaank) ke saath behtar align karte hain.'}`;
      } else {
        introText = `Your current name has a vibration root of ${res.originalRoot}. ${res.alreadyGood ? 'Your name is already in perfect harmony with your Mulaank — no correction is required.' : 'This vibration is not fully compatible with your birth number. Recommended spelling options are listed below.'}`;
      }
      para(introText);
      
      if (res.suggestions.length) {
        h2(activeLang === 'hi' ? 'अनुशंसित वर्तनी' : activeLang === 'hinglish' ? 'Recommended Spellings' : 'Recommended Spellings');
        res.suggestions.slice(0, 5).forEach((s) => {
          chip(`${s.spelling}  (root ${s.root})`, `+${s.improvement}% ${activeLang === 'hi' ? 'मेल' : 'match'}`);
          para(s.reason[activeLang] || s.reason.en, 9.5);
        });
      }
      
      h2(activeLang === 'hi' ? 'हस्ताक्षर दिशानिर्देश और लकी पहला अक्षर' : activeLang === 'hinglish' ? 'Signature Guidelines & Lucky Initial' : 'Signature Guidelines & Lucky Initial');
      if (activeLang === 'hi') {
        para('1. हस्ताक्षर कोण: हमेशा 15 से 30 डिग्री के ऊपर की ओर झुकाव के साथ हस्ताक्षर करें। यह विकास का प्रतिनिधित्व करता है।');
        para('2. बिंदुओं से बचें: हस्ताक्षर के नीचे पीछे जाने वाली रेखा न खींचें या अंत में बिंदु न लगाएं। यह ऊर्जा को रोकता है।');
        para('3. स्पष्टता: अपने नाम का पहला अक्षर बड़ा और स्पष्ट रखें। यह उच्च आत्मविश्वास को दर्शाता है।');
        para(`4. भाग्यशाली पहला अक्षर: आपके मूलांक ${profile.birthday} के आधार पर, सबसे भाग्यशाली पहले अक्षर हैं: ${lucky.numbers.slice(0, 2).join(', ')}.`);
      } else if (activeLang === 'hinglish') {
        para('1. Signature angle: Always sign with an upward slope of 15 to 30 degrees. This represents growth and optimism.');
        para('2. Avoid dots: Do not end your signature with a dot or an underline that goes backwards. It blocks energy.');
        para('3. Legibility: Keep the first letter of your name clear and large. This represents self-confidence.');
        para(`4. Lucky Initial: Based on your Mulaank ${profile.birthday}, the luckiest initials to start your nickname or brand name are: ${lucky.numbers.slice(0, 2).join(', ')}.`);
      } else {
        para('1. Signature angle: Always sign with a slight upward slope (15 to 30 degrees) to invite growth and confidence.');
        para('2. Underline check: Do not end your signature with a dot or draw a line that goes backward underneath.');
        para('3. Clear capital: Keep your first capital letter large and legible to showcase self-esteem.');
        para(`4. Lucky Initial: Based on your Mulank (Birth Number) ${profile.birthday}, the luckiest initials to start a brand or nickname are: ${lucky.numbers.slice(0, 2).join(', ')}.`);
      }
      break;
    }
    case 'mobile_numerology': {
      const num = (((formData as any).mobileNumber || formData.whatsappNumber) || '').replace(/\D/g, '');
      const root = num ? reduceToSingleDigit(num.split('').reduce((a, d) => a + Number(d), 0), false) : profile.birthday;
      
      // Print analyzed mobile number
      chip(activeLang === 'hi' ? 'विश्लेषण किया गया मोबाइल नंबर' : activeLang === 'hinglish' ? 'Analyzed Mobile Number' : 'Analyzed Mobile Number', num || 'N/A');
      
      h2(activeLang === 'hi' ? 'मोबाइल नंबर कंपन' : activeLang === 'hinglish' ? 'Mobile Number Vibration' : 'Mobile Number Vibration');
      
      let vibrationText = '';
      let verdictText = '';
      if (activeLang === 'hi') {
        vibrationText = `आपके मोबाइल नंबर का कंपन मूल ${root} है। मूलांक ${profile.birthday} के लिए शुभ अंक हैं: ${lucky.numbers.join(', ')}.`;
      } else if (activeLang === 'hinglish') {
        vibrationText = `Aapke number ka vibration root ${root} hai. Mulaank ${profile.birthday} ke liye favourable numbers: ${lucky.numbers.join(', ')}.`;
      } else {
        vibrationText = `Your mobile number has a vibration root of ${root}. Best supportive numbers for your birth number (Mulank) ${profile.birthday} are: ${lucky.numbers.join(', ')}.`;
      }
      para(vibrationText);
      
      const friendly = lucky.numbers.map((n) => reduceToSingleDigit(n, false)).includes(root);
      chip(activeLang === 'hi' ? 'नंबर मूल' : 'Number Root', String(root));
      chip(activeLang === 'hi' ? 'अनुकूलता' : 'Compatibility', friendly ? (activeLang === 'hi' ? 'अनुकूल ✓' : 'Supportive ✓') : (activeLang === 'hi' ? 'ध्यान देने की आवश्यकता' : 'Needs attention'));
      
      if (activeLang === 'hi') {
        verdictText = friendly
          ? 'आपका मोबाइल नंबर आपकी ऊर्जा का समर्थन करता है - यह संचार, अवसरों और भाग्य को बढ़ावा देता है।'
          : `आपका मोबाइल नंबर आपके मूलांक के साथ पूर्णतः संरेखित नहीं है। एक नंबर जो मूल ${lucky.numbers.map(n=>reduceToSingleDigit(n,false)).join('/')} पर आता हो, वह आपके लिए बेहतर रहेगा।`;
      } else if (activeLang === 'hinglish') {
        verdictText = friendly
          ? 'Aapka mobile number aapki energy ko support karta hai — communication, opportunities aur luck mein madad milti hai.'
          : 'Aapka mobile number aapke core number (Mulaank) se fully aligned nahi hai. Ek number jo root ' + lucky.numbers.map(n=>reduceToSingleDigit(n,false)).join('/') + ' mein aata ho, behtar rahega.';
      } else {
        verdictText = friendly
          ? 'Your mobile number is highly supportive of your core energy, promoting communication, new opportunities, and good luck.'
          : `Your mobile number is not fully aligned with your birth number (Mulank). A number reducing to root ${lucky.numbers.map(n=>reduceToSingleDigit(n,false)).join('/')} would be much better.`;
      }
      para(verdictText);
      
      h2(activeLang === 'hi' ? 'धन और करियर पर प्रभाव' : activeLang === 'hinglish' ? 'Money & Career Impact' : 'Money & Career Impact');
      const mobileRoots: Record<number, Record<string, string>> = {
        1: { en: 'Excellent for leadership, independent consultants, and sales. It brings authority and recognition.', hi: 'नेतृत्व, स्वतंत्र सलाहकारों और बिक्री के लिए उत्कृष्ट। यह अधिकार और पहचान लाता है।', hinglish: 'Excellent for leadership, independent consultants, aur sales. Authority aur recognition lata hai.' },
        2: { en: 'Good for HR, partnerships, mediators, and creative fields. Promotes cooperation and patience.', hi: 'मानव संसाधन, साझेदारी, मध्यस्थों और रचनात्मक क्षेत्रों के लिए अच्छा है। सहयोग और धैर्य को बढ़ावा देता है।', hinglish: 'HR, partnerships, mediators, aur creative fields ke liye achha. Cooperation aur patience badhata hai.' },
        3: { en: 'Perfect for artists, public speakers, educators, and creators. Expands communication and social networks.', hi: 'कलाकारों, सार्वजनिक वक्ताओं, शिक्षकों और रचनाकारों के लिए बिल्कुल सही। संचार और सामाजिक नेटवर्क का विस्तार करता है।', hinglish: 'Artists, speakers, educators, aur creators ke liye perfect. Communication aur social network badhata hai.' },
        4: { en: 'Supports technical roles, builders, and administrators. Steady but requires hard work and consistency.', hi: 'तकनीकी भूमिकाओं, बिल्डरों और प्रशासकों का समर्थन करता है। स्थिर लेकिन कड़ी मेहनत और निरंतरता की आवश्यकता होती है।', hinglish: 'Technical roles, builders, aur administrators ko support karta hai. Steady par hard work aur consistency chahiye.' },
        5: { en: 'Highly lucky for business, trading, startups, and marketing. Dynamic and quick financial flow.', hi: 'व्यापार, व्यापारिक लेनदेन, स्टार्टअप और विपणन के लिए अत्यधिक भाग्यशाली। गतिशील और त्वरित वित्तीय प्रवाह।', hinglish: 'Business, trading, startups, aur marketing ke liye lucky. Dynamic aur fast money flow lata hai.' },
        6: { en: 'Best for luxury, hospitality, family business, and teaching. Brings peace and customer trust.', hi: 'लक्जरी, आतिथ्य, पारिवारिक व्यवसाय और शिक्षण के लिए सर्वोत्तम। शांति और ग्राहक विश्वास लाता है।', hinglish: 'Luxury, hospitality, family business, aur teaching ke liye best. Peace aur client trust lata hai.' },
        7: { en: 'Good for researchers, tech specialists, and writers. Reflective energy, less focused on raw commerce.', hi: 'शोधकर्ताओं, तकनीकी विशेषज्ञों और लेखकों के लिए अच्छा है। चिंतनशील ऊर्जा, शुद्ध वाणिज्य पर कम केंद्रित।', hinglish: 'Researchers, tech specialists, aur writers ke liye good. Reflective energy, commerce par kam focus.' },
        8: { en: 'Very powerful for finance, large structures, and corporate executive. High growth potential.', hi: 'वित्त, बड़े संगठनों और कॉर्पोरेट अधिकारियों के लिए बहुत शक्तिशाली। उच्च विकास क्षमता।', hinglish: 'Finance, large structures, aur corporate executives ke liye powerful. High growth potential.' },
        9: { en: 'Strong humanitarian appeal, coaching, and international growth. Broad and energetic.', hi: 'मजबूत मानवीय अपील, कोचिंग और अंतर्राष्ट्रीय विकास। व्यापक और ऊर्जावान।', hinglish: 'Humanitarian appeal, coaching, aur international growth. Broad aur energetic.' },
      };
      para(mobileRoots[root]?.[activeLang] || mobileRoots[5]?.[activeLang] || mobileRoots[5].en);
      break;
    }
    case 'vehicle_numerology': {
      const plate = ((formData as any).vehicleNumber || formData.profession || '').toString();
      const va = analyzeVehicle(plate || 'NA', profile.birthday);
      
      // Print analyzed vehicle number
      chip(activeLang === 'hi' ? 'विश्लेषण किया गया वाहन नंबर' : activeLang === 'hinglish' ? 'Analyzed Vehicle Plate' : 'Analyzed Vehicle Plate', plate || 'N/A');
      
      h2(activeLang === 'hi' ? 'वाहन संख्या विश्लेषण' : activeLang === 'hinglish' ? 'Vehicle Number Analysis' : 'Vehicle Number Analysis');
      chip(activeLang === 'hi' ? 'प्लेट योग मूल' : 'Plate Root', String(va.root));
      chip(activeLang === 'hi' ? 'सुरक्षा / भाग्य / सामंजस्य' : 'Safety / Luck / Harmony', `${va.energy.safety} / ${va.energy.luck} / ${va.energy.harmony}`);
      chip(activeLang === 'hi' ? 'आपके साथ मेल' : 'Match with you', va.vsMulank === 'friendly' ? (activeLang === 'hi' ? 'अनुकूल ✓' : 'Friendly ✓') : 'Neutral');
      para(va.verdict[activeLang] || va.verdict.en);
      
      let shubhTxt = '';
      if (activeLang === 'hi') {
        shubhTxt = `मूलांक ${profile.birthday} के लिए शुभ वाहन संख्या वह है जिसका कुल योग ${lucky.numbers.map((n) => reduceToSingleDigit(n, false)).join(', ')} में से किसी पर आए।`;
      } else if (activeLang === 'hinglish') {
        shubhTxt = `Mulaank ${profile.birthday} ke liye shubh vehicle number woh hai jiska root ${lucky.numbers.map((n) => reduceToSingleDigit(n, false)).join(', ')} mein aaye.`;
      } else {
        shubhTxt = `For Mulank (Birth Number) ${profile.birthday}, an auspicious vehicle number is one whose plate sum reduces to: ${lucky.numbers.map((n) => reduceToSingleDigit(n, false)).join(', ')}.`;
      }
      para(shubhTxt);
      
      h2(activeLang === 'hi' ? 'वाहन संख्या के लिए उपाय' : activeLang === 'hinglish' ? 'Remedies for Vehicle Number' : 'Remedies for Vehicle Number');
      para(activeLang === 'hi' ? 'यदि आपकी वाहन संख्या प्रतिकूल या तटस्थ है, तो इन सरल उपायों का उपयोग करें:' : 'If your vehicle number root is neutral or unfriendly with your Mulank, use these remedies to balance the energy:');
      
      if (activeLang === 'hi') {
        bullets([
          'ऊर्जा की रक्षा के लिए डैशबोर्ड पर भगवान गणेश या अपने आराध्य देव की एक छोटी मूर्ति या प्रतीक स्थापित करें।',
          'वाहन की ऊर्जा को शुद्ध करने के लिए ग्लोवबॉक्स या डैशबोर्ड में प्राकृतिक कपूर का एक छोटा टुकड़ा रखें।',
          'यदि प्लेट का कुल योग 4 या 8 है, तो काले सीट कवर से बचें। क्रीम या नीले रंग का उपयोग करें।'
        ]);
      } else if (activeLang === 'hinglish') {
        bullets([
          'Dashboard par ek choti Lord Ganesha ki murti ya symbol lagayein energy protect karne ke liye.',
          'Kapoor (natural camphor) ka ek chota tukda dashboard ya glovebox me rakhein energy clear karne ke liye.',
          'Avoid using dark black or gray seat covers if your vehicle root is 4 or 8. Use beige, cream or blue instead.'
        ]);
      } else {
        bullets([
          'Place a small idol or symbol of Lord Ganesha or your deity on the dashboard for protection.',
          'Keep a small piece of natural camphor inside the glovebox to purify the vehicle energy.',
          'Avoid using dark black or gray seat covers if your vehicle root reduces to 4 or 8. Light beige or blue is preferred.'
        ]);
      }
      break;
    }
    case 'career_numerology': {
      h2(activeLang === 'hi' ? 'व्यावसायिक करियर भविष्यवाणी' : activeLang === 'hinglish' ? 'Consultant-Grade Career Prediction' : 'Consultant-Grade Career Prediction', false);
      
      let mbDetails: any = null;
      let compoundDetails: any = null;
      
      const dob = formData.dateOfBirth;
      let compoundDay = 1;
      if (dob) {
        try {
          const parts = dob.split(/[-\/]/);
          compoundDay = parts[0].length === 4 ? Number(parts[2]) : Number(parts[0]);
        } catch {
          compoundDay = 1;
        }
      }

      try {
        const { supabase } = await import('@/integrations/supabase/client');
        const { data: mb } = await supabase
          .from('nikb_mb_matrix')
          .select('*')
          .eq('mulank', reduceToSingleDigit(profile.birthday, false))
          .eq('bhagyank', reduceToSingleDigit(profile.lifePath, false))
          .maybeSingle();
        mbDetails = mb;
        
        if (compoundDay >= 10) {
          const { data: comp } = await supabase
            .from('nikb_compound_numbers')
            .select('*')
            .eq('compound', compoundDay)
            .maybeSingle();
          compoundDetails = comp;
        }
      } catch (e) {
        console.warn('Failed to load NIKB DB info inside whiteLabelPdf', e);
      }
      
      const mulankStyles: Record<number, string> = {
        1: "Independent and authoritative, you work best as a lead decision-maker or self-employed innovator.",
        2: "Collaborative and highly supportive, you thrive in partnerships, counseling, or diplomatic mediator roles.",
        3: "Creative, expressive, and optimistic, you excel in teaching, marketing, or visual communications.",
        4: "Structured, disciplined, and methodical, you are the backbone of any operation, engineering, or administration setup.",
        5: "Dynamic, adaptable, and free-spirited, you thrive in sales, travel, public relations, or fast-paced startups.",
        6: "Nurturing, responsible, and design-oriented, you excel in community services, counselling, teaching, or creative designs.",
        7: "Analytical, introspective, and research-focused, you are best suited for IT, strategy, writing, or occult studies.",
        8: "Ambitious, highly practical, and executive-driven, you thrive in high-stakes finance, large management structures, or law.",
        9: "Humanitarian, idealistic, and compassionate, you excel in public services, coaching, or global impact programs."
      };

      const bhagyankDestiny: Record<number, string> = {
        1: "Your destiny path guides you towards high-level executive positions, entrepreneurship, and pioneering new industrial paths.",
        2: "Your destiny points towards diplomacy, relationship management, human resources, or creative fine arts.",
        3: "Your destiny aligns with media, consulting, professional speaking, writing, or the entertainment sector.",
        4: "Your destiny is centered around project management, building systems, IT infrastructure, or structural execution.",
        5: "Your destiny path steers you towards international trade, digital commerce, marketing, and dynamic media ventures.",
        6: "Your destiny highlights hospitality, design, counseling, luxury retail, wellness, or teaching roles.",
        7: "Your destiny guides you towards deep scientific research, software analysis, advisory roles, or spiritual teaching.",
        8: "Your destiny lies in large-scale real estate, financial investments, corporate law, or executive operations.",
        9: "Your destiny path directs you to NGOs, medicine, coaching, education, or cross-border expansion initiatives."
      };

      const mStyle = mulankStyles[profile.birthday] || mulankStyles[1];
      const bDest = bhagyankDestiny[profile.lifePath] || bhagyankDestiny[1];

      const mbPersonality = mbDetails?.personality_core || `${mStyle} Your core drive is to operate with integrity while utilizing your natural skills.`;
      const mbCareer = opts?.nikbContext?.mulank_bhagyank_career || mbDetails?.career_profile || `${bDest} Combining your Mulank ${profile.birthday} style with your Bhagyank ${profile.lifePath} direction suggests that you will find maximum satisfaction in fields where you can lead projects using creative or methodical skills.`;
      const compCareer = opts?.nikbContext?.compound_day_career || compoundDetails?.career_impact;
      const mbChallenges = mbDetails?.challenges || `You may face obstacles when your internal work style (Mulank ${profile.birthday}) experiences alignment friction with your destiny expectations (Bhagyank ${profile.lifePath}). Focus on balance and patience.`;
      
      h2(activeLang === 'hi' ? 'व्यक्तित्व कोर' : 'Personality Core', false);
      para(mbPersonality);
      
      h2(activeLang === 'hi' ? 'करियर संरेखण' : 'Your Custom Career Alignment', false);
      para(mbCareer);
      
      if (compCareer) {
        h2(activeLang === 'hi' ? 'जन्म दिन का प्रभाव' : `Vibrational Impact of Birth Day (${compoundDay}th)`, false);
        para(compCareer);
      }
      
      h2(activeLang === 'hi' ? 'व्यावसायिक ताकतें' : 'Professional Strengths & Fit', false);
      bullets(dest.careers);
      
      h2(activeLang === 'hi' ? 'करियर चुनौतियां' : 'Career Pitfalls & Warnings', false);
      para(mbChallenges);
      break;
    }
    case 'baby_name': {
      let luckyRoot = 1;
      const babyDob = formData.dateOfBirth;
      if (babyDob) {
        try {
          const parts = babyDob.split(/[-\/]/);
          const d = parts[0].length === 4 ? Number(parts[2]) : Number(parts[0]);
          const sumDigits = (n: number): number => String(n).split('').reduce((acc, char) => acc + (Number(char) || 0), 0);
          const reduce = (n: number): number => (n <= 9 ? n : reduce(sumDigits(n)));
          luckyRoot = reduce(sumDigits(d));
        } catch {
          luckyRoot = profile.birthday || 1;
        }
      } else {
        luckyRoot = profile.birthday || 1;
      }

      h2(activeLang === 'hi' ? 'शुभ शिशु नाम' : 'Auspicious Baby Names', false);
      para(activeLang === 'hi' ? `शिशु की जन्म तिथि के आधार पर, शुभ अंक ${luckyRoot} है। नीचे इस कंपन से मेल खाते नाम दिए गए हैं:` : `Based on the baby's birth date, the root lucky number is ${luckyRoot}. The following baby name options align perfectly with this vibration to bring harmony and fortune:`);

      if (babyNamesList && babyNamesList.length > 0) {
        babyNamesList.forEach((n: any, idx: number) => {
          ensure(24);
          doc.setFillColor(brand[0], brand[1], brand[2]);
          doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
          doc.roundedRect(M, y, CW, 18, 2, 2, 'F');
          doc.setGState(new (doc as any).GState({ opacity: 1 }));
          
          doc.setTextColor(...soft);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(9);
          doc.text(String(idx + 1).padStart(2, '0'), M + 4, y + 10.5);
          
          doc.setTextColor(...brand);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(11);
          doc.text(n.name, M + 12, y + 10.5);
          
          doc.setTextColor(...soft);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(9.5);
          doc.text(`Root ${n.name_root} (${n.ruling_planet || 'N/A'})`, M + 60, y + 10.5);
          
          doc.setTextColor(...ink);
          doc.setFont('helvetica', 'italic');
          doc.setFontSize(9);
          const meaningText = n.meaning ? `Meaning: ${n.meaning}` : '';
          doc.text(meaningText, M + 110, y + 10.5, { maxWidth: CW - 114 });
          
          y += 22;
        });
      } else {
        let suggestedNames: any[] = [];
        try {
          const { suggestBabyNames } = await import('@/lib/babyNames');
          const babyGender = (formData as any).babyGender || 'unisex';
          const suggested = suggestBabyNames(luckyRoot, babyGender === 'any' ? 'any' : babyGender, 12);
          if (suggested && suggested.length > 0) {
            suggestedNames = suggested.map(n => ({
              name: n.name,
              name_root: n.naamank,
              ruling_planet: RULING_PLANETS[n.naamank] || 'N/A',
              meaning: n.meaning,
            }));
          }
        } catch (err) {
          console.error('Failed to suggest baby names in PDF fallback', err);
        }

        if (suggestedNames.length > 0) {
          suggestedNames.forEach((n: any, idx: number) => {
            ensure(24);
            doc.setFillColor(brand[0], brand[1], brand[2]);
            doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
            doc.roundedRect(M, y, CW, 18, 2, 2, 'F');
            doc.setGState(new (doc as any).GState({ opacity: 1 }));
            
            doc.setTextColor(...soft);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9);
            doc.text(String(idx + 1).padStart(2, '0'), M + 4, y + 10.5);
            
            doc.setTextColor(...brand);
            doc.setFont('helvetica', 'bold');
            doc.setFontSize(11);
            doc.text(n.name, M + 12, y + 10.5);
            
            doc.setTextColor(...soft);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(9.5);
            doc.text(`Root ${n.name_root} (${n.ruling_planet})`, M + 60, y + 10.5);
            
            doc.setTextColor(...ink);
            doc.setFont('helvetica', 'italic');
            doc.setFontSize(9);
            const meaningText = n.meaning ? `Meaning: ${n.meaning}` : '';
            doc.text(meaningText, M + 110, y + 10.5, { maxWidth: CW - 114 });
            
            y += 22;
          });
        } else {
          para(activeLang === 'hi' ? `चयनित मापदंडों के लिए कोई स्वचालित नाम नहीं मिले। कृपया PDF प्रति डाउनलोड करें।` : 'No direct matching baby names found in database for selected parameters. General list is available in the PDF.');
        }
      }

      h2(activeLang === 'hi' ? 'शुभ मुहूर्त' : 'Auspicious Naming Muhurats', false);
      para(activeLang === 'hi' ? `मूलांक और भाग्यशाली दिनों के आधार पर, आगामी शुभ मुहूर्त तिथि सूची:` : `Based on the baby's birth number and lucky days, here are the most auspicious upcoming dates for ceremony:`);
      
      const muhurats: string[] = [];
      const daysOfWeekMap: Record<string, number> = {
        'sunday': 0, 'monday': 1, 'tuesday': 2, 'wednesday': 3, 'thursday': 4, 'friday': 5, 'saturday': 6
      };
      
      const luckyDaysNum = lucky.days.map(d => daysOfWeekMap[d.toLowerCase()]).filter(d => d !== undefined);
      let curr = new Date();
      curr.setDate(curr.getDate() + 3);
      
      while (muhurats.length < 4) {
        if (luckyDaysNum.includes(curr.getDay())) {
          muhurats.push(curr.toLocaleDateString('en-IN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }));
        }
        curr.setDate(curr.getDate() + 1);
      }
      
      bullets(muhurats.map(date => `${date} — Favorable ceremony day.`));
      break;
    }
    case 'compatibility_report': {
      const partnerName = (formData as any).partnerName || 'Partner';
      const partnerDob = (formData as any).partnerDob;
      
      h2(activeLang === 'hi' ? 'रिश्ता अनुकूलता रिपोर्ट' : activeLang === 'hinglish' ? 'Relationship Compatibility Report' : 'Relationship Compatibility Report', false);
      para(activeLang === 'hi' ? `यह रिपोर्ट आपके और आपके साथी (${partnerName}) के बीच ऊर्जा संबंध को दर्शाती है।` : `This report details the energy dynamic between you and your partner (${partnerName}).`);

      if (partnerDob) {
        const partnerMulank = getMulankFromAnyDobFormat(partnerDob);
        const partnerLp = getLifePathFromAnyDobFormat(partnerDob);
        const compat = calculateCompatibility(profile.birthday, partnerMulank);
        
        let dbMatrix: any = null;
        try {
          const { supabase } = await import('@/integrations/supabase/client');
          const n1 = Math.min(profile.birthday, partnerMulank);
          const n2 = Math.max(profile.birthday, partnerMulank);
          const { data } = await supabase
            .from('nikb_compatibility_matrix')
            .select('*')
            .eq('number1', n1)
            .eq('number2', n2)
            .eq('context', 'romantic')
            .maybeSingle();
          dbMatrix = data;
        } catch (e) {
          console.warn('Failed to load DB matrix in compatibility case', e);
        }
        
        const finalScore = dbMatrix?.overall_score ?? compat.score;
        
        chip(activeLang === 'hi' ? 'कुल अनुकूलता स्कोर' : 'Overall Compatibility Score', `${finalScore}% — ${compat.compatibility}`);
        
        h2(activeLang === 'hi' ? 'मूल स्पंदन संबंध' : 'Core Vibrational Dynamic', false);
        const dynamicDesc = dbMatrix?.dynamic_description 
          ? `Your combination of Mulank ${profile.birthday} and ${partnerName}'s Mulank ${partnerMulank} creates the dynamic of "${dbMatrix.dynamic_description}".`
          : `Your combination of Mulank ${profile.birthday} and ${partnerName}'s Mulank ${partnerMulank} is a ${compat.compatibility.toLowerCase()} match.`;
        para(dynamicDesc);
        
        const partnerDestiny = calculateDestiny(partnerName);
        const partnerSoul = calculateSoulUrge(partnerName);
        const commScore = Math.max(45, Math.min(95, 100 - Math.abs(profile.birthday - partnerMulank) * 6 - (Math.abs(profile.destiny - partnerDestiny) % 5) * 4));
        const finScore = Math.max(45, Math.min(95, 100 - Math.abs(profile.destiny - partnerDestiny) * 8 - (Math.abs(profile.birthday - partnerMulank) % 4) * 3));
        const emoScore = Math.max(45, Math.min(95, 100 - Math.abs(profile.birthday - partnerMulank) * 4 - (Math.abs(profile.soulUrge - partnerSoul) % 3) * 6));
        const trustScore = Math.max(45, Math.min(95, 100 - Math.abs(profile.destiny - partnerDestiny) * 5 - (Math.abs(profile.birthday - partnerMulank) % 3) * 5));

        h2(activeLang === 'hi' ? 'संबंध के विभिन्न आयाम' : 'Relationship Dimensions', false);
        chip(activeLang === 'hi' ? '🗣️ संचार सद्भाव' : '🗣️ Communication Harmony', `${dbMatrix?.communication_score ?? commScore}%`);
        chip(activeLang === 'hi' ? '💰 वित्तीय सद्भाव' : '💰 Financial Harmony', `${dbMatrix?.financial_harmony ?? finScore}%`);
        chip(activeLang === 'hi' ? '❤️ भावनात्मक गहराई' : '❤️ Emotional Depth', `${dbMatrix?.emotional_depth ?? emoScore}%`);
        chip(activeLang === 'hi' ? '🤝 आपसी विश्वास' : '🤝 Mutual Trust Score', `${dbMatrix?.trust_score ?? trustScore}%`);
        
        h2(activeLang === 'hi' ? 'इस मेल की मुख्य ताकतें' : 'Key Strengths of this Match', false);
        const strengthsList = dbMatrix?.strengths && dbMatrix.strengths.length > 0
          ? dbMatrix.strengths
          : [compat.strength, 'Complementary energy channels', 'Strong shared potential'];
        bullets(strengthsList);
        
        h2(activeLang === 'hi' ? 'संभावित संघर्ष और चुनौतियां' : 'Potential Conflicts & Challenges', false);
        const challengesList = dbMatrix?.challenges && dbMatrix.challenges.length > 0
          ? dbMatrix.challenges
          : [compat.challenges, 'Different speeds of processing emotions', 'Minor expectation differences'];
        bullets(challengesList);
        
        h2(activeLang === 'hi' ? 'संबंध सुधार के उपाय' : 'Relationship Remedies (How to strengthen the bond)', false);
        const makeItWork = dbMatrix?.make_it_work ?? 'Focus on open communication and respect each other\'s natural style of expression.';
        para(makeItWork);
        
      } else {
        para('Please provide your partner\'s date of birth to calculate exact compatibility.');
      }
      break;
    }
    case 'marriage_report': {
      h2(activeLang === 'hi' ? 'विवाह मुहूर्त समयरेखा' : 'Marriage Timing Timeline (5-Year Window)', false);
      para(activeLang === 'hi' ? 'आपके व्यक्तिगत वर्ष चक्र के आधार पर, विवाह के लिए अनुकूल तिथियां:' : 'Based on your Personal Year cycle, here is a detailed 5-year forecast highlighting favorable, neutral, and challenging phases for marriage:');
      
      const dob = formData.dateOfBirth;
      if (dob) {
        const startYear = new Date().getFullYear();
        
        for (let i = 0; i < 5; i++) {
          const targetYear = startYear + i;
          const py = calculatePersonalYearForYear(dob, targetYear);
          
          let ratingStr = 'Neutral';
          let ratingStars = '★★★☆☆';
          let desc = '';
          
          if (py === 2) {
            ratingStr = activeLang === 'hi' ? 'अत्यधिक अनुकूल' : 'Highly Favorable';
            ratingStars = '★★★★★';
            desc = 'Moon-ruled year of partnership, romance, and emotional union. Ideal for legalizing a relationship and domestic bonding.';
          } else if (py === 6) {
            ratingStr = activeLang === 'hi' ? 'अत्यधिक अनुकूल' : 'Highly Favorable';
            ratingStars = '★★★★★';
            desc = 'Venus-ruled year of home, family responsibility, and love. The absolute strongest year for successful marriages and family harmony.';
          } else if (py === 1) {
            ratingStr = activeLang === 'hi' ? 'अनुकूल' : 'Favorable';
            ratingStars = '★★★★☆';
            desc = 'Sun-ruled year of fresh starts and new beginnings. Favorable for launching a new life phase and starting a household.';
          } else if (py === 4) {
            ratingStr = activeLang === 'hi' ? 'अनुकूल' : 'Favorable';
            ratingStars = '★★★★☆';
            desc = 'Rahu-ruled year of stability, foundations, and structure. Favorable for building a secure, down-to-earth marriage structure.';
          } else if (py === 8) {
            ratingStr = activeLang === 'hi' ? 'अनुकूल / कार्मिक' : 'Favorable / Karmic';
            ratingStars = '★★★☆☆';
            desc = 'Saturn-ruled year of destiny and material results. Union brings status and structural growth, though requires mature responsibility.';
          } else if (py === 3) {
            ratingStr = 'Neutral';
            ratingStars = '★★★☆☆';
            desc = 'Jupiter-ruled year of social expansion and joy. High social activity, but focus is scattered. Union is happy but needs grounding.';
          } else if (py === 5) {
            ratingStr = activeLang === 'hi' ? 'चुनौतीपूर्ण' : 'Challenging';
            ratingStars = '★★☆☆☆';
            desc = 'Mercury-ruled year of change, freedom, and transition. High possibility of unexpected shifts. Harder to commit or establish roots.';
          } else if (py === 7) {
            ratingStr = activeLang === 'hi' ? 'चुनौतीपूर्ण / आत्मनिरीक्षण' : 'Challenging / Introspective';
            ratingStars = '★★☆☆☆';
            desc = 'Ketu-ruled year of solitude, spiritual seeking, and inner reflection. Can lead to emotional isolation. Focus should be on inner alignment.';
          } else if (py === 9) {
            ratingStr = activeLang === 'hi' ? 'चुनौतीपूर्ण / अंत' : 'Challenging / Endings';
            ratingStars = '★★☆☆☆';
            desc = 'Mars-ruled year of endings and cycle closures. Clean up old emotional baggage before starting a new commitment.';
          }
          
          ensure(26);
          doc.setFillColor(brand[0], brand[1], brand[2]);
          doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
          doc.roundedRect(M, y, CW, 20, 2, 2, 'F');
          doc.setGState(new (doc as any).GState({ opacity: 1 }));
          
          doc.setTextColor(...brand);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(12);
          doc.text(`${targetYear} (Personal Year ${py})`, M + 4, y + 8);
          
          const ratingColor = (py === 2 || py === 6) ? accent : brand;
          doc.setTextColor(...ratingColor);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(10);
          doc.text(`${ratingStr} ${ratingStars}`, W - M - 4, y + 8, { align: 'right' });
          
          doc.setTextColor(...ink);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(9.5);
          
          const favMonths: string[] = [];
          const monthNames = [
            'January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
          ];
          for (let m = 1; m <= 12; m++) {
            const pm = reduceToSingleDigit(py + m, false);
            if (pm === 2 || pm === 6 || pm === 3) {
              favMonths.push(monthNames[m - 1]);
            }
          }
          const fullDesc = `${desc} (Favorable Month Windows: ${favMonths.join(', ')})`;
          doc.text(fullDesc, M + 4, y + 15, { maxWidth: CW - 8 });
          
          y += 24;
        }
      } else {
        para('Please verify your date of birth is filled.');
      }

      h2(activeLang === 'hi' ? 'वैवाहिक सामंजस्य मार्गदर्शन' : 'Marriage Harmony Guidance');
      if (activeLang === 'hi') {
        bullets([
          'एक-दूसरे के व्यक्तिगत वर्ष चक्रों का सम्मान करें। सही समय संघर्षों को कम करने में मदद करता है।',
          'भावनात्मक दूरी को रोकने के लिए व्यक्तिगत वर्ष 5 या 7 चरणों के दौरान खुला संवाद बनाए रखें।',
          'सकारात्मक ब्रह्मांडीय संरेखण को कैप्चर करने के लिए एक अनुकूल महीने के दौरान शादी समारोह करें।'
        ]);
      } else {
        bullets([
          'Respect each other\'s personal year cycles. Favorable timing helps reduce unnecessary conflicts.',
          'Maintain open communication during personal year 5 or 7 phases to prevent emotional distance.',
          'Perform the wedding ceremony during a favorable month to capture positive cosmic alignment.'
        ]);
      }
      break;
    }
    case 'business_numerology': {
      const bizName = (formData as any).businessName || formData.displayName || formData.fullBirthName || 'My Business';
      const analysis = calculateBusinessVibration(bizName, formData.dateOfBirth);
      
      // Print analyzed business name
      chip(activeLang === 'hi' ? 'विश्लेषण किया गया व्यावसायिक नाम' : activeLang === 'hinglish' ? 'Analyzed Business Name' : 'Analyzed Business Name', bizName);
      
      h2(activeLang === 'hi' ? 'व्यावसायिक अंकशास्त्र रिपोर्ट' : activeLang === 'hinglish' ? 'Business Numerology Report' : 'Business Numerology Report', false);
      para(`This report details the energy alignment for your business name: "${bizName}".`);
      
      chip(activeLang === 'hi' ? 'व्यावसायिक नाम मूल' : 'Business Name Root', String(analysis.brand.root));
      chip(activeLang === 'hi' ? 'आर्कटाइप नाम' : 'Archetype Name', `${analysis.archetype.name} — ${analysis.archetype.tagline}`);
      
      if (analysis.founderAlignment) {
        chip(activeLang === 'hi' ? 'संस्थापक के साथ संरेखण' : 'Founder Alignment', analysis.founderAlignment.verdict === 'aligned' ? (activeLang === 'hi' ? 'अत्यधिक संरेखित ✓' : 'Highly Aligned ✓') : 'Neutral Compatibility');
        para(`Your Life Path ${analysis.founderAlignment.lifePath} aligns with the business root ${analysis.brand.root} nicely.`);
      }
      
      h2(activeLang === 'hi' ? 'आर्कटाइप ऊर्जा विवरण' : 'Archetype Energy Description', false);
      const archetypesMeaning: Record<number, string> = {
        1: "Pioneering energy. Perfect for startups, tech, innovation, and businesses that want to dominate the market first.",
        2: "Supportive and collaborative energy. Great for consulting, advisory, healthcare, partnerships, and service-based business.",
        3: "Creative and communication energy. Great for marketing agency, PR, event companies, restaurants, and entertainment.",
        4: "Stable and systematic energy. Great for construction, real estate, manufacturing, logistics, and legal services.",
        5: "Fast-moving and versatile energy. Great for e-commerce, trading, travel, media, and tech.",
        6: "Warm and family-oriented energy. Great for lifestyle, luxury items, design, cosmetics, education, and NGOs.",
        7: "Premium, sage, and specialist energy. Great for research labs, luxury boutiques, strategy firms, and spiritual centers.",
        8: "Scale and wealth magnet. Great for banking, finance, investment, large factories, and corporate business.",
        9: "Purpose-driven and broad appeal. Great for public welfare, training institutes, global brands, and healers.",
      };
      para(archetypesMeaning[analysis.archetype.number] || archetypesMeaning[1]);
      
      h2(activeLang === 'hi' ? 'वर्तनी सुधार सुझाव' : 'Spelling Tweaks to Optimize Business Name', false);
      para('If your business name has a neutral or mismatch vibration, minor tweaks can align it to a lucky business number (like 1, 5, 6, or 9) for smoother flow and growth:');
      const targetRoots = [1, 5, 6, 9].filter(r => r !== analysis.archetype.number);
      const tweaks = suggestBrandTweaks(bizName, targetRoots[0] || 1);
      if (tweaks && tweaks.length > 0) {
        tweaks.forEach((t) => {
          chip(`${t.name} (root ${t.root})`, t.change);
        });
      } else {
        para("Your brand name is already aligned or has a stable root. Keep active branding strong!");
      }
      break;
    }
    case 'property_numerology': {
      const propNo = (formData as any).propertyNumber || '';
      const propType = (formData as any).propertyType || 'House';
      const analysis = analyzeHouse(propNo, profile.birthday);
      
      // Print analyzed property number
      chip(activeLang === 'hi' ? 'विश्लेषण की गई संपत्ति संख्या' : activeLang === 'hinglish' ? 'Analyzed Property Number' : 'Analyzed Property Number', propNo || 'N/A');
      
      h2(activeLang === 'hi' ? 'संपत्ति और घर संख्या रिपोर्ट' : activeLang === 'hinglish' ? 'Property & House Number Report' : 'Property & House Number Report', false);
      para(`Analyzing the vibration for ${propType} number: "${propNo}".`);
      
      chip(activeLang === 'hi' ? 'पते का मूल अंक' : 'Address Root Number', String(analysis.root));
      chip(activeLang === 'hi' ? 'मालिक के साथ अनुकूलता' : 'Vibe Compatibility with Owner', analysis.vsMulank === 'friendly' ? (activeLang === 'hi' ? 'अनुकूल ✓' : 'Harmonious Match ✓') : 'Neutral Match');
      
      h2(activeLang === 'hi' ? 'संपत्ति ऊर्जा अर्थ' : 'Property Energy Meaning', false);
      para(analysis.meaning[activeLang] || analysis.meaning.en);
      
      h2(activeLang === 'hi' ? 'विभिन्न दिशा स्कोर' : 'Address Energy Dimension Scores', false);
      chip('Prosperity Score', `${analysis.energy.prosperity}%`);
      chip('Peace Score', `${analysis.energy.peace}%`);
      chip('Relationship Harmony', `${analysis.energy.relationships}%`);
      chip('Health Vibration', `${analysis.energy.health}%`);
      
      h2(activeLang === 'hi' ? 'पते के लिए शुभ उपाय' : 'Auspicious Remedies for Your Address', false);
      para(analysis.remedy[activeLang] || analysis.remedy.en);
      break;
    }
    case 'shani_sade_sati': {
      h2(activeLang === 'hi' ? 'शनि साढ़े साती एवं ढैय्या विश्लेषण' : 'Shani Sade Sati & Dhaiya Analysis', false);
      para('Saturn is the divine taskmaster representing discipline, endurance, and karmic justice.');
      chip('Active Sade Sati Phase', 'Phase 2: Peak / Janma Shani (Crown Transit)');
      chip('Kantaka & Ashtama Shani Status', 'Neutral Gochar Support');
      chip('Expected Duration', '2024 to 2029 (Peak turning into Setting phase)');
      h2('Classical Lal Kitab & Vedic Remedies');
      bullets([
        'Chant Om Sham Shanaishcharaya Namah 108 times on Saturdays after sunset.',
        'Light a mustard oil lamp under a sacred Peepal tree every Saturday.',
        'Donate black sesame seeds, iron vessels, or black blankets to the underprivileged.',
        'Avoid starting non-essential financial speculation on Saturdays.'
      ]);
      break;
    }
    case 'pitra_dosh_karmic': {
      h2(activeLang === 'hi' ? 'पितृ दोष एवं पूर्वज कर्म विश्लेषण' : 'Pitra Dosh & Ancestral Karma Analysis', false);
      para('Analysis of the 9th house (Bhagya Sthana), Surya placement, and Rahu conjunctions.');
      chip('Pitra Dosh Severity Level', 'Mild / Anshik Rin (Easily pacified)');
      chip('Governing Ancestral Lineage', 'Paternal Lineage (Surya-Rahu affinity)');
      h2('Ancestral Blessing & Shradh Vidhi');
      bullets([
        'Offer water mixed with black sesame to the Sun and ancestors on Amavasya mornings.',
        'Feed cows (Gau Seva) with green grass and wheat dough on monthly new moon days.',
        'Perform sacred Narayan Bali or Pitra Gayatri Japa for generational prosperity.',
        'Plant a Peepal or Banyan tree sapling in a public or temple precinct.'
      ]);
      break;
    }
    case 'wealth_yogas_kundli': {
      h2(activeLang === 'hi' ? 'महाधन योग एवं लक्ष्मी प्राप्ति विश्लेषण' : 'Dhana Yogas & Laxmi Prapti Blueprint', false);
      para('Evaluation of 2nd (Accumulated Wealth), 5th (Speculative Fortune), 9th (Grace), and 11th (Gains) houses.');
      chip('Key Raja / Dhana Yogas Active', 'Gajakesari Yoga & Lakshmi Yoga');
      chip('Optimal Wealth Channels', 'Real Estate, Technology, Strategic Investments, Fine Commodities');
      chip('10-Year Wealth Dasha Cycle', 'High Acceleration Phase Commencing');
      h2('Wealth Activation & Yantra Ritual');
      bullets([
        'Install a 24K Gold-Plated Shree Yantra in the North-East Ishan corner of home/office.',
        'Chant the sacred Kanakadhara Stotram or Om Shreem Mahalakshmiyei Namah on Fridays.',
        'Keep the North treasury locker clutter-free with a silver coin energized in Ganga water.'
      ]);
      break;
    }
    case 'health_vitality_kundli': {
      h2(activeLang === 'hi' ? 'मेडिकल एस्ट्रोलॉजी एवं स्वास्थ्य विश्लेषण' : 'Medical Astrology & Vitality Blueprint', false);
      para('Evaluation of 6th house (Ari Sthana), 8th house (Longevity), and planetary balance on the 7 bodily Chakras.');
      chip('Ayurvedic Tridosha Dominance', 'Pitta-Vata Dynamic Balance');
      chip('Vitality & Immunity Score', '88% Resilience Quotient');
      chip('Sensitive Organ Systems', 'Digestive Fire (Jatharagni) & Nervous Tension');
      h2('Holistic Lifestyle & Cosmic Health Prescription');
      bullets([
        'Practice daily Surya Namaskar at sunrise to nourish the Solar Plexus (Manipura) chakra.',
        'Consume warm herbal infusions of Ashwagandha and Tulsi to ground excess Vata.',
        'Avoid erratic sleeping habits during Saturn transits; maintain regular circadian rhythm.'
      ]);
      break;
    }
    case 'foreign_settlement_travel': {
      h2(activeLang === 'hi' ? 'विदेश यात्रा एवं पीआर सेटलमेंट योग' : 'Foreign Settlement & PR Immigration Report', false);
      para('Analysis of the 12th house (Foreign Lands), 9th house (Long Journeys), and Rahu mobility yogas.');
      chip('Foreign Settlement Probability', '92% Strong Indication');
      chip('Favorable Geographic Directions', 'North-West & South-West Quadrants');
      chip('Optimal Visa Processing Window', 'Next 3 to 6 Months during Rahu/Jupiter Sub-period');
      h2('Immigration Obstacle Clearance Remedies');
      bullets([
        'Offer coconut in running water on Wednesdays to pacify traveling Rahu.',
        'Keep essential immigration dossiers in the North-West Vayu corner before submission.',
        'Chant the Hanuman Chalisa on Tuesdays for smooth clearance across international borders.'
      ]);
      break;
    }
    case 'mangal_dosha_analysis': {
      h2(activeLang === 'hi' ? 'सम्पूर्ण मांगलिक दोष एवं निवारण' : 'Complete Manglik Dosha & Remedies Report', false);
      para('Precise examination of Mars placement in the 1st, 2nd, 4th, 7th, 8th, or 12th houses with 28 classical cancellation rules.');
      chip('Manglik Classification', 'Anshik / Cancelled by Jupiter Aspect (Bhanga Yoga)');
      chip('Marital Harmony Compatibility', 'Safe with both Manglik and Non-Manglik Partners');
      chip('Mars Energy Channel', 'High Drive, Courage, and Athletic Leadership');
      h2('Mars Propitiation & Peaceful Union Rituals');
      bullets([
        'Recite the Mangal Beej Mantra: Om Kram Kreem Kroum Sah Bhaumaya Namah.',
        'Wear natural Red Coral (Moonga) in copper or gold on the ring finger after consultation.',
        'Feed sweet roti or jaggery to monkeys or cows on Tuesday mornings.'
      ]);
      break;
    }
    default: {
      h2(activeLang === 'hi' ? 'जीवन का उद्देश्य' : 'Life Purpose');
      para(lp.purpose);
      h2(activeLang === 'hi' ? 'शक्तियां' : 'Strengths');
      bullets(lp.strengths);
      h2(activeLang === 'hi' ? 'करियर पथ' : 'Career Paths');
      bullets(dest.careers);
    }
  }

  // Core Life Pillars, Lo Shu Grid, and Pinnacles (Paid Report Additions)
  try {
    const { calculateVedicProfile } = await import('@/lib/vedicNumerology');
    const { calculateLifePillars } = await import('@/lib/lifePillars');
    const { calculateLoshuGrid, calculatePinnacleCycles } = await import('@/lib/advancedNumerology');

    const vedic = calculateVedicProfile(formData.dateOfBirth, profile.personalYear);
    const pillars = calculateLifePillars(vedic, {
      lifePath: profile.lifePath,
      destiny: profile.destiny,
      personalYear: profile.personalYear
    });
    const loshu = calculateLoshuGrid(formData.dateOfBirth, formData.fullBirthName);
    const pinnacles = calculatePinnacleCycles(formData.dateOfBirth);

    // Life Pillars
    h2('Core Life Pillars');
    para('Your life is structured around five core pillars of energy. Here is the alignment and vibrational analysis for each area:');

    chip('💼 Career & Success', `Work Style: ${pillars.career.workStyle.primary}`);
    para(`Job vs Business: Job ${pillars.career.jobVsBusinessScore.job}% | Business ${pillars.career.jobVsBusinessScore.business}%\nVerdict: ${pillars.career.jobVsBusinessScore.verdict}`, 9.5);

    chip('❤️ Love & Relationships', `Love Vibration: ${pillars.love.loveVibration.type}`);
    para(`Attachment Style: ${pillars.love.relationshipStyle.attachment}\nSoul Lesson: ${pillars.love.soulLesson}`, 9.5);

    chip('💰 Money & Abundance', `Money Vibration: ${pillars.money.moneyVibration.type}`);
    para(`Earning Path: ${pillars.money.earningPath.primary}\nInvestment Style: ${pillars.money.investmentStyle}`, 9.5);

    chip('🌿 Health & Wellbeing', `Balance Score: ${pillars.health.balanceScore}%`);
    para(`Stress Pattern: ${pillars.health.stressPattern}\nKey chakra to focus on balancing: ${vedic.remedies.weakChakra}`, 9.5);

    chip('✨ Personal Growth', `Growth Archetype: ${pillars.growth.archetype}`);
    para(`Karmic Lesson: ${pillars.growth.karmicLesson}\nLife Theme: ${pillars.growth.lifeTheme}`, 9.5);

    // Lo Shu Grid
    ensure(80);
    h2('Lo Shu Magic Square');
    para('The Lo Shu Grid is an ancient 3x3 magic square that reveals active strengths and missing lessons based on your birth date and name.');

    const cellW = 22;
    const cellH = 18;
    const gridW = cellW * 3;
    const gridH = cellH * 3;
    const startX = (W - gridW) / 2;
    const startY = y;

    const gridLayout = [
      [4, 9, 2],
      [3, 5, 7],
      [8, 1, 6]
    ];

    gridLayout.forEach((row, ri) => {
      row.forEach((num, ci) => {
        const cellX = startX + ci * cellW;
        const cellY = startY + ri * cellH;
        const isPresent = loshu.present.includes(num);

        if (isPresent) {
          doc.setFillColor(brand[0], brand[1], brand[2]);
          doc.setGState(new (doc as any).GState({ opacity: 0.12 }));
          doc.roundedRect(cellX, cellY, cellW - 2, cellH - 2, 2, 2, 'F');
          doc.setGState(new (doc as any).GState({ opacity: 1 }));
          
          doc.setTextColor(...brand);
          doc.setFont('helvetica', 'bold');
          doc.setFontSize(13);
          doc.text(String(num), cellX + cellW / 2 - 1, cellY + cellH / 2 + 1.5, { align: 'center' });
        } else {
          doc.setFillColor(240, 238, 245);
          doc.roundedRect(cellX, cellY, cellW - 2, cellH - 2, 2, 2, 'F');
          
          doc.setTextColor(...soft);
          doc.setFont('helvetica', 'normal');
          doc.setFontSize(10);
          doc.text('-', cellX + cellW / 2 - 1, cellY + cellH / 2 + 1.5, { align: 'center' });
        }
      });
    });
    
    y = startY + gridH + 8;

    if (loshu.missing?.length) {
      para(`Missing numbers to strengthen: ${loshu.missing.join(', ')}`, 9.5);
    }
    if (loshu.analysis?.arrows?.length) {
      para(`Planes of Strength: ${loshu.analysis.arrows.join(' • ')}`, 9.5);
    }

    // Pinnacle Cycles
    h2('Pinnacle Life Cycles');
    para('Pinnacles represent four distinct phases of your life, each governed by a specific number that defines your core opportunities and experiences.');

    pinnacles.forEach((cycle, index) => {
      chip(`Phase ${index + 1} (Ages ${cycle.ages})`, `Pinnacle Number: ${cycle.number}`);
      para(`Theme: ${cycle.theme.en}\nOpportunity: ${cycle.opportunities[0]}\nChallenge: ${cycle.challenges[0]}`, 9.5);
    });

  } catch (e) {
    console.warn('[pdf] extra paid sections failed:', e);
  }

  // remedies (common closing, personalised by number)
  if (remedy) {
    h2('Personalised Remedies');
    const rlist: string[] = [];
    rlist.push('Planet: ' + remedy.planet);
    rlist.push('Gemstone: ' + remedy.gemstone.en);
    rlist.push('Lucky colour: ' + remedy.color.en + ' (wear on ' + remedy.day + ')');
    rlist.push('Mantra: ' + remedy.mantra);
    (remedy.remedies.hinglish || remedy.remedies.en || []).forEach((t) => rlist.push(t));
    bullets(rlist);
  }

  // ---- AI personalized sections (paid only, if available) ----
  const ai = opts?.aiContent;
  if (ai && ai.summary) {
    newPage();
    h2('Your Personalised Reading');
    para(ai.summary);
    if (ai.strengths?.length) { h2('Your Key Strengths'); bullets(ai.strengths); }
    if (ai.risks?.length) { h2('Watch-outs'); bullets(ai.risks); }
    if (ai.actions?.length) { h2('Your Action Plan'); bullets(ai.actions); }
    if (ai.luckyFocus) { h2('Lucky Focus'); para(ai.luckyFocus); }
    if (ai.timeline) { h2('Favourable Period Ahead'); para(ai.timeline); }
    if (ai.closingNote) { para(ai.closingNote, 11); }
  }

  // closing CTA
  ensure(40);
  doc.setFillColor(...brand);
  doc.setGState(new (doc as any).GState({ opacity: 0.06 }));
  doc.roundedRect(M, y, CW, 30, 3, 3, 'F');
  doc.setGState(new (doc as any).GState({ opacity: 1 }));
  doc.setTextColor(...brand);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Thank you for trusting ' + b.company_name, W / 2, y + 12, { align: 'center' });
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...soft);
  if (b.contact_line) doc.text(b.contact_line, W / 2, y + 21, { align: 'center' });

  const safe = (formData.displayName || formData.fullBirthName || 'report').replace(/[^a-z0-9]/gi, '_');
  doc.save(`${REPORT_TITLES[reportKey].replace(/[^a-z0-9]/gi, '_')}_${safe}.pdf`);
};
