import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { toast } from 'sonner';
import { Save, Image as ImageIcon } from 'lucide-react';

interface BrandingRow {
  company_name: string;
  logo_url: string;
  brand_color: string;
  accent_color: string;
  tagline: string;
  footer_text: string;
  contact_line: string;
  website: string;
}

const EMPTY: BrandingRow = {
  company_name: 'AnkJyotish AI', logo_url: '', brand_color: '#7c3aed', accent_color: '#f0a500',
  tagline: 'Numerology that changes lives', footer_text: 'Generated by AnkJyotish AI • ankjyotishai.com',
  contact_line: '', website: 'ankjyotishai.com',
};

export default function BrandingManager() {
  const [row, setRow] = useState<BrandingRow>(EMPTY);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    (async () => {
      const { data } = await supabase.from('app_branding').select('*').eq('id', 1).maybeSingle();
      if (data) setRow({ ...EMPTY, ...data });
      setLoading(false);
    })();
  }, []);

  const set = (k: keyof BrandingRow, v: string) => setRow((p) => ({ ...p, [k]: v }));

  const save = async () => {
    setSaving(true);
    const { error } = await supabase.from('app_branding').upsert({ id: 1, ...row, updated_at: new Date().toISOString() });
    setSaving(false);
    if (error) { toast.error('Save failed: ' + error.message); return; }
    toast.success('Branding saved — naye PDF par lagega');
  };

  if (loading) return <p className="text-sm text-muted-foreground">Loading branding…</p>;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2"><ImageIcon className="w-4 h-4" /> White-label Branding (PDF/Reports)</CardTitle>
        <p className="text-sm text-muted-foreground">Ye settings har report PDF par lagti hain — logo, naam, colour, footer.</p>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="grid sm:grid-cols-2 gap-4">
          <div>
            <Label>Company name</Label>
            <Input value={row.company_name} onChange={(e) => set('company_name', e.target.value)} />
          </div>
          <div>
            <Label>Website</Label>
            <Input value={row.website} onChange={(e) => set('website', e.target.value)} placeholder="ankjyotishai.com" />
          </div>
        </div>

        <div>
          <Label>Logo upload (PDF par yahi dikhega)</Label>
          <div className="flex flex-wrap items-center gap-3 mt-1">
            <input
              type="file"
              accept="image/png,image/jpeg,image/jpg,image/webp"
              onChange={(e) => {
                const file = e.target.files?.[0];
                if (!file) return;
                if (file.size > 800 * 1024) { toast.error('Logo 800KB se chhota rakho'); return; }
                const reader = new FileReader();
                reader.onload = () => { if (typeof reader.result === 'string') { set('logo_url', reader.result); toast.success('Logo loaded — Save dabao'); } };
                reader.readAsDataURL(file);
              }}
              className="text-sm file:mr-3 file:py-1.5 file:px-3 file:rounded-md file:border-0 file:bg-primary file:text-primary-foreground file:text-sm file:cursor-pointer"
            />
            {row.logo_url && (
              <div className="inline-flex items-center gap-2 p-2 rounded border border-border bg-muted/30">
                <img src={row.logo_url} alt="logo preview" className="h-10 w-10 object-contain" onError={(e) => ((e.target as HTMLImageElement).style.display = 'none')} />
                <span className="text-xs text-muted-foreground">Preview</span>
                <Button size="sm" variant="ghost" className="h-7 text-destructive" onClick={() => set('logo_url', '')}>Hatao</Button>
              </div>
            )}
          </div>
          <p className="text-xs text-muted-foreground mt-1">PNG/JPG, transparent background best. Customer ko sirf yahi logo PDF par dikhega.</p>
        </div>

        <div className="grid sm:grid-cols-2 gap-4">
          <div>
            <Label>Brand colour (heading)</Label>
            <div className="flex gap-2">
              <Input type="color" value={row.brand_color} onChange={(e) => set('brand_color', e.target.value)} className="w-14 p-1 h-10" />
              <Input value={row.brand_color} onChange={(e) => set('brand_color', e.target.value)} />
            </div>
          </div>
          <div>
            <Label>Accent colour (highlights)</Label>
            <div className="flex gap-2">
              <Input type="color" value={row.accent_color} onChange={(e) => set('accent_color', e.target.value)} className="w-14 p-1 h-10" />
              <Input value={row.accent_color} onChange={(e) => set('accent_color', e.target.value)} />
            </div>
          </div>
        </div>

        <div>
          <Label>Tagline (cover par)</Label>
          <Input value={row.tagline} onChange={(e) => set('tagline', e.target.value)} />
        </div>
        <div>
          <Label>Footer text (har page niche)</Label>
          <Input value={row.footer_text} onChange={(e) => set('footer_text', e.target.value)} />
        </div>
        <div>
          <Label>Contact line (WhatsApp/email — optional)</Label>
          <Input value={row.contact_line} onChange={(e) => set('contact_line', e.target.value)} placeholder="WhatsApp: +91-... • support@..." />
        </div>

        <Button onClick={save} disabled={saving} className="gap-2">
          <Save className="w-4 h-4" /> {saving ? 'Saving…' : 'Save branding'}
        </Button>
      </CardContent>
    </Card>
  );
}
