-- =====================================================================
-- 08_branding.sql  — White-label branding settings (single row)
-- PDF/reports par logo, company name, colour, footer — admin editable.
-- Resell ke liye: koi bhi brand ke naam se report nikal sakte ho.
-- Supabase project: kassdsugfktqptsxzqhr  (naya project NAHI)
-- =====================================================================

CREATE TABLE IF NOT EXISTS public.app_branding (
  id int PRIMARY KEY DEFAULT 1,
  company_name text NOT NULL DEFAULT 'AnkJyotish AI',
  logo_url text DEFAULT '',                 -- public image URL (png/jpg)
  brand_color text NOT NULL DEFAULT '#7c3aed',   -- heading / accents
  accent_color text NOT NULL DEFAULT '#f0a500',  -- highlights
  tagline text DEFAULT 'Numerology that changes lives',
  footer_text text DEFAULT 'Generated by AnkJyotish AI • ankjyotishai.com',
  contact_line text DEFAULT 'WhatsApp: +91-00000-00000 • support@ankjyotishai.com',
  website text DEFAULT 'ankjyotishai.com',
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT single_row CHECK (id = 1)
);

-- seed the single row (id=1) if not present
INSERT INTO public.app_branding (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;

-- grants
GRANT SELECT ON public.app_branding TO anon, authenticated;
GRANT INSERT, UPDATE ON public.app_branding TO authenticated;

-- RLS: sab padh sakte (PDF generate ke liye), sirf admin likh sake
ALTER TABLE public.app_branding ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS branding_read ON public.app_branding;
CREATE POLICY branding_read ON public.app_branding
  FOR SELECT USING (true);

DROP POLICY IF EXISTS branding_write ON public.app_branding;
CREATE POLICY branding_write ON public.app_branding
  FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());

-- Verify:
-- SELECT company_name, logo_url, brand_color FROM public.app_branding WHERE id = 1;
